version: '3'
services:

  eureka-service:
    build:
      context: eureka-service/
      dockerfile: Dockerfile
    image: eureka-service
    ports:
      - '8761:8761'

  zuul-service:
    build:
      context: zuul-service/
      dockerfile: Dockerfile
    image: zuul-service
    links:
      - eureka-service
    ports:
      - '8080:8080'

  rabbitmq:
    image: 'rabbitmq:management-alpine'
    ports:
    - '5672:5672'
    - '15672:15672'

  spectral-service:
    build:
      context: spectral-service/
      dockerfile: Dockerfile
    image: spectral-service
    links:
      - eureka-service

  project-service:
    build:
      context: project-service/
      dockerfile: Dockerfile
    image: project-service
    links:
      - rabbitmq
      - eureka-service
    environment:
      RABBIT_HOST: rabbitmq
    volumes:
    - 'D:\docker\project-service\projects:/data/projects'

  generation-service:
    build:
      context: generation-service/
      dockerfile: Dockerfile
    image: generation-service
    links:
      - rabbitmq
      - eureka-service
    environment:
      RABBIT_HOST: rabbitmq
    volumes:
      - 'D:\docker\project-service\projects:/data/projects'