version: '3'
services:

  eureka-service:
    build:
      context: eureka-service/
      dockerfile: Dockerfile
    image: eureka-service
    ports:
      - '8761:8761'

  zuul-service:
    build:
      context: zuul-service/
      dockerfile: Dockerfile
    image: zuul-service
    links:
      - eureka-service
    ports:
      - '8080:8080'

  spectral-service:
    build:
      context: spectral-service/
      dockerfile: Dockerfile
    image: spectral-service
    links:
      - eureka-service

  project-service:
    build:
      context: project-service/
      dockerfile: Dockerfile
    image: project-service
    links:
      - eureka-service
    volumes:
    - '/d/docker/project-service/projects:/data/projects'