//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model.schedblock;

import com.prototype.ot.microservices.projectservice.model.SkyCoordinatesT;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AtmosphericCalParametersT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AtmosphericCalParametersT">
 *   &lt;complexContent>
 *     &lt;extension base="{Alma/ObsPrep/SchedBlock}CalibratorParametersT">
 *       &lt;sequence>
 *         &lt;element name="useHotLoad" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="skyPosition" type="{Alma/ValueTypes}SkyCoordinatesT"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AtmosphericCalParametersT", propOrder = {
    "useHotLoad",
    "skyPosition"
})
public class AtmosphericCalParametersT
    extends CalibratorParametersT
{

    @XmlElement(defaultValue = "false")
    protected boolean useHotLoad;
    @XmlElement(required = true)
    protected SkyCoordinatesT skyPosition;

    /**
     * Gets the value of the useHotLoad property.
     * 
     */
    public boolean isUseHotLoad() {
        return useHotLoad;
    }

    /**
     * Sets the value of the useHotLoad property.
     * 
     */
    public void setUseHotLoad(boolean value) {
        this.useHotLoad = value;
    }

    /**
     * Gets the value of the skyPosition property.
     * 
     * @return
     *     possible object is
     *     {@link SkyCoordinatesT }
     *     
     */
    public SkyCoordinatesT getSkyPosition() {
        return skyPosition;
    }

    /**
     * Sets the value of the skyPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkyCoordinatesT }
     *     
     */
    public void setSkyPosition(SkyCoordinatesT value) {
        this.skyPosition = value;
    }

}
