//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model.schedblock;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FrequencySwitchingCycleT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FrequencySwitchingCycleT">
 *   &lt;complexContent>
 *     &lt;extension base="{Alma/ObsPrep/SchedBlock}AbstractSwitchingCycleT">
 *       &lt;sequence>
 *         &lt;element name="FrequencySwitchingState" type="{Alma/ObsPrep/SchedBlock}FrequencySwitchingStateT" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FrequencySwitchingCycleT", propOrder = {
    "frequencySwitchingState"
})
public class FrequencySwitchingCycleT
    extends AbstractSwitchingCycleT
{

    @XmlElement(name = "FrequencySwitchingState", required = true)
    protected List<FrequencySwitchingStateT> frequencySwitchingState;

    /**
     * Gets the value of the frequencySwitchingState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the frequencySwitchingState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFrequencySwitchingState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FrequencySwitchingStateT }
     * 
     * 
     */
    public List<FrequencySwitchingStateT> getFrequencySwitchingState() {
        if (frequencySwitchingState == null) {
            frequencySwitchingState = new ArrayList<FrequencySwitchingStateT>();
        }
        return this.frequencySwitchingState;
    }

}
