//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model.schedblock;

import com.prototype.ot.microservices.projectservice.model.valuetypes.TimeT;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A control class for SchedBlocks. Includes controls such as the desired execution count of the SB and the maximum integration time per execution.
 * 
 * <p>Java class for SchedBlockControlT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SchedBlockControlT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sBMaximumTime" type="{Alma/ValueTypes}TimeT"/>
 *         &lt;element name="indefiniteRepeat" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="executionCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="runQuicklook" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SchedBlockControlT", propOrder = {
    "sbMaximumTime",
    "indefiniteRepeat",
    "executionCount",
    "runQuicklook"
})
public class SchedBlockControlT {

    @XmlElement(name = "sBMaximumTime", required = true)
    protected TimeT sbMaximumTime;
    @XmlElement(defaultValue = "false")
    protected boolean indefiniteRepeat;
    @XmlElement(defaultValue = "1")
    protected int executionCount;
    @XmlElement(defaultValue = "true")
    protected boolean runQuicklook;

    /**
     * Gets the value of the sbMaximumTime property.
     * 
     * @return
     *     possible object is
     *     {@link TimeT }
     *     
     */
    public TimeT getSBMaximumTime() {
        return sbMaximumTime;
    }

    /**
     * Sets the value of the sbMaximumTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeT }
     *     
     */
    public void setSBMaximumTime(TimeT value) {
        this.sbMaximumTime = value;
    }

    /**
     * Gets the value of the indefiniteRepeat property.
     * 
     */
    public boolean isIndefiniteRepeat() {
        return indefiniteRepeat;
    }

    /**
     * Sets the value of the indefiniteRepeat property.
     * 
     */
    public void setIndefiniteRepeat(boolean value) {
        this.indefiniteRepeat = value;
    }

    /**
     * Gets the value of the executionCount property.
     * 
     */
    public int getExecutionCount() {
        return executionCount;
    }

    /**
     * Sets the value of the executionCount property.
     * 
     */
    public void setExecutionCount(int value) {
        this.executionCount = value;
    }

    /**
     * Gets the value of the runQuicklook property.
     * 
     */
    public boolean isRunQuicklook() {
        return runQuicklook;
    }

    /**
     * Sets the value of the runQuicklook property.
     * 
     */
    public void setRunQuicklook(boolean value) {
        this.runQuicklook = value;
    }

}
