//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model.schedblock;

import com.prototype.ot.microservices.projectservice.model.MagnitudeT;
import com.prototype.ot.microservices.projectservice.model.valuetypes.AngleT;
import com.prototype.ot.microservices.projectservice.model.valuetypes.FluxT;
import com.prototype.ot.microservices.projectservice.model.valuetypes.FrequencyT;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Known Properties for a given source. There may be many of these per source.
 * 
 * <p>Java class for SourcePropertyT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SourcePropertyT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sourceFrequency" type="{Alma/ValueTypes}FrequencyT"/>
 *         &lt;element name="sourceFluxI" type="{Alma/ValueTypes}FluxT" minOccurs="0"/>
 *         &lt;element name="sourceDiameter" type="{Alma/ValueTypes}AngleT" minOccurs="0"/>
 *         &lt;element name="sourceFluxQ" type="{Alma/ValueTypes}FluxT" minOccurs="0"/>
 *         &lt;element name="sourceFluxU" type="{Alma/ValueTypes}FluxT" minOccurs="0"/>
 *         &lt;element name="sourceFluxV" type="{Alma/ValueTypes}FluxT" minOccurs="0"/>
 *         &lt;element name="visibleMagnitude" type="{Alma/ValueTypes}MagnitudeT" minOccurs="0"/>
 *         &lt;element name="dateOfMeasurement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SourcePropertyT", propOrder = {
    "sourceFrequency",
    "sourceFluxI",
    "sourceDiameter",
    "sourceFluxQ",
    "sourceFluxU",
    "sourceFluxV",
    "visibleMagnitude",
    "dateOfMeasurement"
})
public class SourcePropertyT {

    @XmlElement(required = true)
    protected FrequencyT sourceFrequency;
    protected FluxT sourceFluxI;
    protected AngleT sourceDiameter;
    protected FluxT sourceFluxQ;
    protected FluxT sourceFluxU;
    protected FluxT sourceFluxV;
    protected MagnitudeT visibleMagnitude;
    protected String dateOfMeasurement;

    /**
     * Gets the value of the sourceFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link FrequencyT }
     *     
     */
    public FrequencyT getSourceFrequency() {
        return sourceFrequency;
    }

    /**
     * Sets the value of the sourceFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrequencyT }
     *     
     */
    public void setSourceFrequency(FrequencyT value) {
        this.sourceFrequency = value;
    }

    /**
     * Gets the value of the sourceFluxI property.
     * 
     * @return
     *     possible object is
     *     {@link FluxT }
     *     
     */
    public FluxT getSourceFluxI() {
        return sourceFluxI;
    }

    /**
     * Sets the value of the sourceFluxI property.
     * 
     * @param value
     *     allowed object is
     *     {@link FluxT }
     *     
     */
    public void setSourceFluxI(FluxT value) {
        this.sourceFluxI = value;
    }

    /**
     * Gets the value of the sourceDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link AngleT }
     *     
     */
    public AngleT getSourceDiameter() {
        return sourceDiameter;
    }

    /**
     * Sets the value of the sourceDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleT }
     *     
     */
    public void setSourceDiameter(AngleT value) {
        this.sourceDiameter = value;
    }

    /**
     * Gets the value of the sourceFluxQ property.
     * 
     * @return
     *     possible object is
     *     {@link FluxT }
     *     
     */
    public FluxT getSourceFluxQ() {
        return sourceFluxQ;
    }

    /**
     * Sets the value of the sourceFluxQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link FluxT }
     *     
     */
    public void setSourceFluxQ(FluxT value) {
        this.sourceFluxQ = value;
    }

    /**
     * Gets the value of the sourceFluxU property.
     * 
     * @return
     *     possible object is
     *     {@link FluxT }
     *     
     */
    public FluxT getSourceFluxU() {
        return sourceFluxU;
    }

    /**
     * Sets the value of the sourceFluxU property.
     * 
     * @param value
     *     allowed object is
     *     {@link FluxT }
     *     
     */
    public void setSourceFluxU(FluxT value) {
        this.sourceFluxU = value;
    }

    /**
     * Gets the value of the sourceFluxV property.
     * 
     * @return
     *     possible object is
     *     {@link FluxT }
     *     
     */
    public FluxT getSourceFluxV() {
        return sourceFluxV;
    }

    /**
     * Sets the value of the sourceFluxV property.
     * 
     * @param value
     *     allowed object is
     *     {@link FluxT }
     *     
     */
    public void setSourceFluxV(FluxT value) {
        this.sourceFluxV = value;
    }

    /**
     * Gets the value of the visibleMagnitude property.
     * 
     * @return
     *     possible object is
     *     {@link MagnitudeT }
     *     
     */
    public MagnitudeT getVisibleMagnitude() {
        return visibleMagnitude;
    }

    /**
     * Sets the value of the visibleMagnitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link MagnitudeT }
     *     
     */
    public void setVisibleMagnitude(MagnitudeT value) {
        this.visibleMagnitude = value;
    }

    /**
     * Gets the value of the dateOfMeasurement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfMeasurement() {
        return dateOfMeasurement;
    }

    /**
     * Sets the value of the dateOfMeasurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfMeasurement(String value) {
        this.dateOfMeasurement = value;
    }

}
