//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model.obsproject;

import com.prototype.ot.microservices.projectservice.model.valuetypes.AngleT;
import com.prototype.ot.microservices.projectservice.model.valuetypes.LengthT;
import com.prototype.ot.microservices.projectservice.model.valuetypes.SpeedT;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * As part of the Preconditions, outlines the weather constraints that must be satisfied before execution can begin.
 * 
 * <p>Java class for WeatherConstraintsT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WeatherConstraintsT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="maxPWVC" type="{Alma/ValueTypes}LengthT"/>
 *         &lt;element name="seeing" type="{Alma/ValueTypes}AngleT"/>
 *         &lt;element name="phaseStability" type="{Alma/ValueTypes}AngleT"/>
 *         &lt;element name="maxWindVelocity" type="{Alma/ValueTypes}SpeedT"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WeatherConstraintsT", namespace = "Alma/ObsPrep/ObsProject", propOrder = {
    "maxPWVC",
    "seeing",
    "phaseStability",
    "maxWindVelocity"
})
public class WeatherConstraintsT {

    @XmlElement(required = true)
    protected LengthT maxPWVC;
    @XmlElement(required = true)
    protected AngleT seeing;
    @XmlElement(required = true)
    protected AngleT phaseStability;
    @XmlElement(required = true)
    protected SpeedT maxWindVelocity;

    /**
     * Gets the value of the maxPWVC property.
     * 
     * @return
     *     possible object is
     *     {@link LengthT }
     *     
     */
    public LengthT getMaxPWVC() {
        return maxPWVC;
    }

    /**
     * Sets the value of the maxPWVC property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthT }
     *     
     */
    public void setMaxPWVC(LengthT value) {
        this.maxPWVC = value;
    }

    /**
     * Gets the value of the seeing property.
     * 
     * @return
     *     possible object is
     *     {@link AngleT }
     *     
     */
    public AngleT getSeeing() {
        return seeing;
    }

    /**
     * Sets the value of the seeing property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleT }
     *     
     */
    public void setSeeing(AngleT value) {
        this.seeing = value;
    }

    /**
     * Gets the value of the phaseStability property.
     * 
     * @return
     *     possible object is
     *     {@link AngleT }
     *     
     */
    public AngleT getPhaseStability() {
        return phaseStability;
    }

    /**
     * Sets the value of the phaseStability property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleT }
     *     
     */
    public void setPhaseStability(AngleT value) {
        this.phaseStability = value;
    }

    /**
     * Gets the value of the maxWindVelocity property.
     * 
     * @return
     *     possible object is
     *     {@link SpeedT }
     *     
     */
    public SpeedT getMaxWindVelocity() {
        return maxWindVelocity;
    }

    /**
     * Sets the value of the maxWindVelocity property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpeedT }
     *     
     */
    public void setMaxWindVelocity(SpeedT value) {
        this.maxWindVelocity = value;
    }

}
