/*
 * ALMA - Atacama Large Millimeter Array
 * Copyright (c) UKATC - UK Astronomy Technology Centre, Science and Technology Facilities Council, 2018
 * (in the framework of the ALMA collaboration).
 * All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Base class for Science Goals. Holds the name and a reference to the ObsUnitSet containing the program implementation of the goal.
 * 
 * <p>Java class for AbstractScienceGoalT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractScienceGoalT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ObsUnitSetRef" type="{Alma/ObsPrep/ObsProject}ObsProjectRefT" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractScienceGoalT", namespace = "Alma/ObsPrep/ObsProject", propOrder = {
    "name",
    "note",
    "obsUnitSetRef"
})
@XmlSeeAlso({
    ObservatoryGoalT.class,
    OpticalPointingScienceGoalT.class,
    ScienceGoalT.class
})
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME)
@JsonSubTypes({
        @JsonSubTypes.Type(value = ObservatoryGoalT.class, name = "ObservatoryGoalT"),
        @JsonSubTypes.Type(value = OpticalPointingScienceGoalT.class, name = "OpticalPointingScienceGoalT"),
        @JsonSubTypes.Type(value = ScienceGoalT.class, name = "ScienceGoalT")
})
public abstract class AbstractScienceGoalT {

    @XmlElement(required = true)
    private String name;
    private String note;
    @XmlElement(name = "ObsUnitSetRef")
    private ObsProjectRefT obsUnitSetRef;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the obsUnitSetRef property.
     * 
     * @return
     *     possible object is
     *     {@link ObsProjectRefT }
     *     
     */
    public ObsProjectRefT getObsUnitSetRef() {
        return obsUnitSetRef;
    }

    /**
     * Sets the value of the obsUnitSetRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObsProjectRefT }
     *     
     */
    public void setObsUnitSetRef(ObsProjectRefT value) {
        this.obsUnitSetRef = value;
    }

}
