/*
 * ALMA - Atacama Large Millimeter Array
 * Copyright (c) UKATC - UK Astronomy Technology Centre, Science and Technology Facilities Council, 2018
 * (in the framework of the ALMA collaboration).
 * All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Abstract correlator configuration class containing the attributes common to all correlator configurations.
 * 
 * <p>Java class for AbstractCorrelatorConfigurationT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractCorrelatorConfigurationT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="integrationDuration" type="{Alma/ValueTypes}TimeT"/>
 *         &lt;element name="channelAverageDuration" type="{Alma/ValueTypes}TimeT"/>
 *         &lt;element name="enable180DegreeWalshFunction" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="enable90DegreeWalshFunction" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *       &lt;attribute name="aPCDataSets" default="AP_CORRECTED">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="AP_UNCORRECTED"/>
 *             &lt;enumeration value="AP_CORRECTED"/>
 *             &lt;enumeration value="AP_CORRECTED+AP_UNCORRECTED"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="cAM" default="NORMAL">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="FAST"/>
 *             &lt;enumeration value="NORMAL"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="lOOffsettingMode" default="NONE">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="NONE"/>
 *             &lt;enumeration value="TWO_LOS"/>
 *             &lt;enumeration value="THREE_LOS"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractCorrelatorConfigurationT", propOrder = {
    "integrationDuration",
    "channelAverageDuration",
    "enable180DegreeWalshFunction",
    "enable90DegreeWalshFunction"
})
@XmlSeeAlso({
    ACACorrelatorConfigurationT.class,
    BLCorrelatorConfigurationT.class
})
public abstract class AbstractCorrelatorConfigurationT {

    @XmlElement(required = true)
    private TimeT integrationDuration;
    @XmlElement(required = true)
    private TimeT channelAverageDuration;
    @XmlElement(defaultValue = "false")
    private boolean enable180DegreeWalshFunction;
    @XmlElement(defaultValue = "false")
    private boolean enable90DegreeWalshFunction;
    @XmlAttribute(name = "aPCDataSets")
    private String apcDataSets;
    @XmlAttribute(name = "cAM")
    private String cam;
    @XmlAttribute(name = "lOOffsettingMode")
    private String loOffsettingMode;

    /**
     * Gets the value of the integrationDuration property.
     * 
     * @return
     *     possible object is
     *     {@link TimeT }
     *     
     */
    public TimeT getIntegrationDuration() {
        return integrationDuration;
    }

    /**
     * Sets the value of the integrationDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeT }
     *     
     */
    public void setIntegrationDuration(TimeT value) {
        this.integrationDuration = value;
    }

    /**
     * Gets the value of the channelAverageDuration property.
     * 
     * @return
     *     possible object is
     *     {@link TimeT }
     *     
     */
    public TimeT getChannelAverageDuration() {
        return channelAverageDuration;
    }

    /**
     * Sets the value of the channelAverageDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeT }
     *     
     */
    public void setChannelAverageDuration(TimeT value) {
        this.channelAverageDuration = value;
    }

    /**
     * Gets the value of the enable180DegreeWalshFunction property.
     * 
     */
    public boolean isEnable180DegreeWalshFunction() {
        return enable180DegreeWalshFunction;
    }

    /**
     * Sets the value of the enable180DegreeWalshFunction property.
     * 
     */
    public void setEnable180DegreeWalshFunction(boolean value) {
        this.enable180DegreeWalshFunction = value;
    }

    /**
     * Gets the value of the enable90DegreeWalshFunction property.
     * 
     */
    public boolean isEnable90DegreeWalshFunction() {
        return enable90DegreeWalshFunction;
    }

    /**
     * Sets the value of the enable90DegreeWalshFunction property.
     * 
     */
    public void setEnable90DegreeWalshFunction(boolean value) {
        this.enable90DegreeWalshFunction = value;
    }

    /**
     * Gets the value of the apcDataSets property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPCDataSets() {
        if (apcDataSets == null) {
            return "AP_CORRECTED";
        } else {
            return apcDataSets;
        }
    }

    /**
     * Sets the value of the apcDataSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPCDataSets(String value) {
        this.apcDataSets = value;
    }

    /**
     * Gets the value of the cam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAM() {
        if (cam == null) {
            return "NORMAL";
        } else {
            return cam;
        }
    }

    /**
     * Sets the value of the cam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAM(String value) {
        this.cam = value;
    }

    /**
     * Gets the value of the loOffsettingMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOOffsettingMode() {
        if (loOffsettingMode == null) {
            return "NONE";
        } else {
            return loOffsettingMode;
        }
    }

    /**
     * Sets the value of the loOffsettingMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOOffsettingMode(String value) {
        this.loOffsettingMode = value;
    }

}
