/*
 * ALMA - Atacama Large Millimeter Array
 * Copyright (c) UKATC - UK Astronomy Technology Centre, Science and Technology Facilities Council, 2018
 * (in the framework of the ALMA collaboration).
 * All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Concrete version of a correlator configuration for the ACA correlator.
 * 
 * <p>Java class for ACACorrelatorConfigurationT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ACACorrelatorConfigurationT">
 *   &lt;complexContent>
 *     &lt;extension base="{Alma/ObsPrep/SchedBlock}AbstractCorrelatorConfigurationT">
 *       &lt;sequence>
 *         &lt;element name="ACABaseBandConfig" type="{Alma/ObsPrep/SchedBlock}ACABaseBandConfigT" maxOccurs="4"/>
 *         &lt;element name="ACAPhaseSwitchingConfiguration" type="{Alma/ObsPrep/SchedBlock}ACAPhaseSwitchingConfigurationT"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACACorrelatorConfigurationT", propOrder = {
    "acaBaseBandConfig",
    "acaPhaseSwitchingConfiguration"
})
public class ACACorrelatorConfigurationT
    extends AbstractCorrelatorConfigurationT
{

    @XmlElement(name = "ACABaseBandConfig", required = true)
    private List<ACABaseBandConfigT> acaBaseBandConfig;
    @XmlElement(name = "ACAPhaseSwitchingConfiguration", required = true)
    private ACAPhaseSwitchingConfigurationT acaPhaseSwitchingConfiguration;

    /**
     * Gets the value of the acaBaseBandConfig property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acaBaseBandConfig property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getACABaseBandConfig().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ACABaseBandConfigT }
     * 
     * 
     */
    public List<ACABaseBandConfigT> getACABaseBandConfig() {
        if (acaBaseBandConfig == null) {
            acaBaseBandConfig = new ArrayList<>();
        }
        return this.acaBaseBandConfig;
    }

    /**
     * Gets the value of the acaPhaseSwitchingConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link ACAPhaseSwitchingConfigurationT }
     *     
     */
    public ACAPhaseSwitchingConfigurationT getACAPhaseSwitchingConfiguration() {
        return acaPhaseSwitchingConfiguration;
    }

    /**
     * Sets the value of the acaPhaseSwitchingConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACAPhaseSwitchingConfigurationT }
     *     
     */
    public void setACAPhaseSwitchingConfiguration(ACAPhaseSwitchingConfigurationT value) {
        this.acaPhaseSwitchingConfiguration = value;
    }

}
