/*
 * ALMA - Atacama Large Millimeter Array
 * Copyright (c) UKATC - UK Astronomy Technology Centre, Science and Technology Facilities Council, 2018
 * (in the framework of the ALMA collaboration).
 * All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines the phase switching configuration 180 degrees which is performed in the ACA correlator.
 * 
 * <p>Java class for ACAPhaseSwitchingConfigurationT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ACAPhaseSwitchingConfigurationT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="doD180modulation" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="doD180demodulation" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACAPhaseSwitchingConfigurationT", propOrder = {
    "doD180Modulation",
    "doD180Demodulation"
})
public class ACAPhaseSwitchingConfigurationT {

    @XmlElement(name = "doD180modulation", defaultValue = "true")
    private boolean doD180Modulation;
    @XmlElement(name = "doD180demodulation", defaultValue = "true")
    private boolean doD180Demodulation;

    /**
     * Gets the value of the doD180Modulation property.
     * 
     */
    public boolean isDoD180Modulation() {
        return doD180Modulation;
    }

    /**
     * Sets the value of the doD180Modulation property.
     * 
     */
    public void setDoD180Modulation(boolean value) {
        this.doD180Modulation = value;
    }

    /**
     * Gets the value of the doD180Demodulation property.
     * 
     */
    public boolean isDoD180Demodulation() {
        return doD180Demodulation;
    }

    /**
     * Sets the value of the doD180Demodulation property.
     * 
     */
    public void setDoD180Demodulation(boolean value) {
        this.doD180Demodulation = value;
    }

}
