//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BeamSwitchingCycleT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BeamSwitchingCycleT">
 *   &lt;complexContent>
 *     &lt;extension base="{Alma/ObsPrep/SchedBlock}AbstractSwitchingCycleT">
 *       &lt;sequence>
 *         &lt;element name="BeamSwitchingState" type="{Alma/ObsPrep/SchedBlock}BeamSwitchingStateT" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="mode" default="STEPS">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="STEPS"/>
 *             &lt;enumeration value="TRIANGULAR"/>
 *             &lt;enumeration value="SINUSOIDAL"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BeamSwitchingCycleT", propOrder = {
    "beamSwitchingState"
})
public class BeamSwitchingCycleT
    extends AbstractSwitchingCycleT
{

    @XmlElement(name = "BeamSwitchingState", required = true)
    private List<BeamSwitchingStateT> beamSwitchingState;
    @XmlAttribute(name = "mode")
    private String mode;

    /**
     * Gets the value of the beamSwitchingState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the beamSwitchingState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBeamSwitchingState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BeamSwitchingStateT }
     * 
     * 
     */
    public List<BeamSwitchingStateT> getBeamSwitchingState() {
        if (beamSwitchingState == null) {
            beamSwitchingState = new ArrayList<>();
        }
        return this.beamSwitchingState;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMode() {
        if (mode == null) {
            return "STEPS";
        } else {
            return mode;
        }
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMode(String value) {
        this.mode = value;
    }

}
