//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model;

import com.prototype.ot.microservices.projectservice.model.valuetypes.AngleT;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Outlines the calibration requirements of any given ObsUnit (ObsUnitSet or SB). Details are still a little fuzzy. This information may be used by the Scheduler in order to determine whether existing calibrations can be used for this SB, and by the observing script to set parameters for the various calibration scans.
 * 
 * <p>Java class for CalibrationRequirementsT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CalibrationRequirementsT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pointingAccuracy" type="{Alma/ValueTypes}AngleT"/>
 *         &lt;element name="bandpassAccuracy" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="polarizationAccuracy" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CalibrationRequirementsT", namespace = "Alma/ObsPrep/ObsProject", propOrder = {
    "pointingAccuracy",
    "bandpassAccuracy",
    "polarizationAccuracy"
})
public class CalibrationRequirementsT {

    @XmlElement(required = true)
    protected AngleT pointingAccuracy;
    protected double bandpassAccuracy;
    protected double polarizationAccuracy;

    /**
     * Gets the value of the pointingAccuracy property.
     * 
     * @return
     *     possible object is
     *     {@link AngleT }
     *     
     */
    public AngleT getPointingAccuracy() {
        return pointingAccuracy;
    }

    /**
     * Sets the value of the pointingAccuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleT }
     *     
     */
    public void setPointingAccuracy(AngleT value) {
        this.pointingAccuracy = value;
    }

    /**
     * Gets the value of the bandpassAccuracy property.
     * 
     */
    public double getBandpassAccuracy() {
        return bandpassAccuracy;
    }

    /**
     * Sets the value of the bandpassAccuracy property.
     * 
     */
    public void setBandpassAccuracy(double value) {
        this.bandpassAccuracy = value;
    }

    /**
     * Gets the value of the polarizationAccuracy property.
     * 
     */
    public double getPolarizationAccuracy() {
        return polarizationAccuracy;
    }

    /**
     * Sets the value of the polarizationAccuracy property.
     * 
     */
    public void setPolarizationAccuracy(double value) {
        this.polarizationAccuracy = value;
    }

}
