//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model.obsproject;

import com.prototype.ot.microservices.projectservice.model.TimeT;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Provides the execution control limits on any given ObsUnit (ObsUnitSet or SB), in terms of items like the maximum time allowed, the user and tac priorities etc.
 * 
 * <p>Java class for ControlBlockT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ControlBlockT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="maximumTime" type="{Alma/ValueTypes}TimeT"/>
 *         &lt;element name="userPriority" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="estimatedExecutionTime" type="{Alma/ValueTypes}TimeT"/>
 *         &lt;element name="tacPriority" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="aggregatedExecutionCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *       &lt;attribute name="arrayRequested" default="TWELVE-M">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="ACA"/>
 *             &lt;enumeration value="SEVEN-M"/>
 *             &lt;enumeration value="TP-Array"/>
 *             &lt;enumeration value="TWELVE-M"/>
 *             &lt;enumeration value="ALMA"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ControlBlockT", namespace = "Alma/ObsPrep/ObsProject", propOrder = {
    "maximumTime",
    "userPriority",
    "estimatedExecutionTime",
    "tacPriority",
    "aggregatedExecutionCount"
})
@XmlSeeAlso({
    ObsUnitControlT.class
})
public class ControlBlockT {

    @XmlElement(required = true)
    protected TimeT maximumTime;
    protected int userPriority;
    @XmlElement(required = true)
    protected TimeT estimatedExecutionTime;
    protected int tacPriority;
    @XmlElement(defaultValue = "1")
    protected int aggregatedExecutionCount;
    @XmlAttribute(name = "arrayRequested")
    protected String arrayRequested;

    /**
     * Gets the value of the maximumTime property.
     * 
     * @return
     *     possible object is
     *     {@link TimeT }
     *     
     */
    public TimeT getMaximumTime() {
        return maximumTime;
    }

    /**
     * Sets the value of the maximumTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeT }
     *     
     */
    public void setMaximumTime(TimeT value) {
        this.maximumTime = value;
    }

    /**
     * Gets the value of the userPriority property.
     * 
     */
    public int getUserPriority() {
        return userPriority;
    }

    /**
     * Sets the value of the userPriority property.
     * 
     */
    public void setUserPriority(int value) {
        this.userPriority = value;
    }

    /**
     * Gets the value of the estimatedExecutionTime property.
     * 
     * @return
     *     possible object is
     *     {@link TimeT }
     *     
     */
    public TimeT getEstimatedExecutionTime() {
        return estimatedExecutionTime;
    }

    /**
     * Sets the value of the estimatedExecutionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeT }
     *     
     */
    public void setEstimatedExecutionTime(TimeT value) {
        this.estimatedExecutionTime = value;
    }

    /**
     * Gets the value of the tacPriority property.
     * 
     */
    public int getTacPriority() {
        return tacPriority;
    }

    /**
     * Sets the value of the tacPriority property.
     * 
     */
    public void setTacPriority(int value) {
        this.tacPriority = value;
    }

    /**
     * Gets the value of the aggregatedExecutionCount property.
     * 
     */
    public int getAggregatedExecutionCount() {
        return aggregatedExecutionCount;
    }

    /**
     * Sets the value of the aggregatedExecutionCount property.
     * 
     */
    public void setAggregatedExecutionCount(int value) {
        this.aggregatedExecutionCount = value;
    }

    /**
     * Gets the value of the arrayRequested property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrayRequested() {
        if (arrayRequested == null) {
            return "TWELVE-M";
        } else {
            return arrayRequested;
        }
    }

    /**
     * Sets the value of the arrayRequested property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrayRequested(String value) {
        this.arrayRequested = value;
    }

}
