//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Sppecialization of a Field for an elliptical map. Not yet implemented
 * 
 * <p>Java class for EllipseT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EllipseT">
 *   &lt;complexContent>
 *     &lt;extension base="{Alma/ObsPrep/ObsProject}FieldT">
 *       &lt;sequence>
 *         &lt;element name="semiMajor" type="{Alma/ValueTypes}AngleT"/>
 *         &lt;element name="semiMinor" type="{Alma/ValueTypes}AngleT"/>
 *         &lt;element name="pAMajor" type="{Alma/ValueTypes}AngleT"/>
 *         &lt;element name="spacing" type="{Alma/ValueTypes}UserAngleT"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EllipseT", namespace = "Alma/ObsPrep/ObsProject", propOrder = {
    "semiMajor",
    "semiMinor",
    "paMajor",
    "spacing"
})
public class EllipseT
    extends FieldT
{

    @XmlElement(required = true)
    protected AngleT semiMajor;
    @XmlElement(required = true)
    protected AngleT semiMinor;
    @XmlElement(name = "pAMajor", required = true)
    protected AngleT paMajor;
    @XmlElement(required = true)
    protected UserAngleT spacing;

    /**
     * Gets the value of the semiMajor property.
     * 
     * @return
     *     possible object is
     *     {@link AngleT }
     *     
     */
    public AngleT getSemiMajor() {
        return semiMajor;
    }

    /**
     * Sets the value of the semiMajor property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleT }
     *     
     */
    public void setSemiMajor(AngleT value) {
        this.semiMajor = value;
    }

    /**
     * Gets the value of the semiMinor property.
     * 
     * @return
     *     possible object is
     *     {@link AngleT }
     *     
     */
    public AngleT getSemiMinor() {
        return semiMinor;
    }

    /**
     * Sets the value of the semiMinor property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleT }
     *     
     */
    public void setSemiMinor(AngleT value) {
        this.semiMinor = value;
    }

    /**
     * Gets the value of the paMajor property.
     * 
     * @return
     *     possible object is
     *     {@link AngleT }
     *     
     */
    public AngleT getPAMajor() {
        return paMajor;
    }

    /**
     * Sets the value of the paMajor property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleT }
     *     
     */
    public void setPAMajor(AngleT value) {
        this.paMajor = value;
    }

    /**
     * Gets the value of the spacing property.
     * 
     * @return
     *     possible object is
     *     {@link UserAngleT }
     *     
     */
    public UserAngleT getSpacing() {
        return spacing;
    }

    /**
     * Sets the value of the spacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAngleT }
     *     
     */
    public void setSpacing(UserAngleT value) {
        this.spacing = value;
    }

}
