//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Holds references to a set of Ordered Targets. These targets will be observed together in this group.
 * 
 * <p>Java class for ObservingGroupT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObservingGroupT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderedTarget" type="{Alma/ObsPrep/SchedBlock}OrderedTargetT" maxOccurs="unbounded"/>
 *         &lt;element name="mainTargetRef" type="{Alma/ObsPrep/SchedBlock}SchedBlockRefT" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObservingGroupT", propOrder = {
    "index",
    "name",
    "orderedTarget",
    "mainTargetRef"
})
public class ObservingGroupT {

    private int index;
    @XmlElement(required = true)
    private String name;
    @XmlElement(name = "OrderedTarget", required = true)
    private List<OrderedTargetT> orderedTarget;
    private SchedBlockRefT mainTargetRef;

    /**
     * Gets the value of the index property.
     * 
     */
    public int getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     */
    public void setIndex(int value) {
        this.index = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the orderedTarget property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderedTarget property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderedTarget().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderedTargetT }
     * 
     * 
     */
    public List<OrderedTargetT> getOrderedTarget() {
        if (orderedTarget == null) {
            orderedTarget = new ArrayList<>();
        }
        return this.orderedTarget;
    }

    /**
     * Gets the value of the mainTargetRef property.
     * 
     * @return
     *     possible object is
     *     {@link SchedBlockRefT }
     *     
     */
    public SchedBlockRefT getMainTargetRef() {
        return mainTargetRef;
    }

    /**
     * Sets the value of the mainTargetRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchedBlockRefT }
     *     
     */
    public void setMainTargetRef(SchedBlockRefT value) {
        this.mainTargetRef = value;
    }

}
