//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObsProposalEntityT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObsProposalEntityT">
 *   &lt;complexContent>
 *     &lt;restriction base="{Alma/CommonEntity}EntityT">
 *       &lt;attribute name="entityTypeName" use="required" type="{Alma/CommonEntity}EntityTypeNameT" fixed="ObsProposal" />
 *       &lt;attribute name="schemaVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="13" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObsProposalEntityT", namespace = "Alma/ObsPrep/ObsProposal")
public class ObsProposalEntityT
    extends EntityT
{

    public ObsProposalEntityT() {
        super();
        this.setEntityTypeName("ObsProposal");
    }

}
