//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ObsProposal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObsProposal">
 *   &lt;complexContent>
 *     &lt;extension base="{Alma/ObsPrep/ObsProject}ObsPhaseT">
 *       &lt;sequence>
 *         &lt;element name="ObsProposalEntity" type="{Alma/ObsPrep/ObsProposal}ObsProposalEntityT"/>
 *         &lt;element name="DocumentsRef" type="{Alma/Obsprep/ObsAttachment}ObsAttachmentRefT" minOccurs="0"/>
 *         &lt;element name="ObsProjectRef" type="{Alma/ObsPrep/ObsProject}ObsProjectRefT"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="abstract" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="relatedProposals" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="previousProposals" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateReceived" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="cycle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="studentProject" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="continuation" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="recentPublications" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scientificCategoryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="proposalTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scientificCategoryString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="proposalTypeString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="keyword" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="keywordCode" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="resubmittedProjectCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isResubmission" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="duplicateObservationsJustification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrincipalInvestigator" type="{Alma/ObsPrep/ObsProposal}InvestigatorT"/>
 *         &lt;element name="CoInvestigator" type="{Alma/ObsPrep/ObsProposal}InvestigatorT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CoPrincipalInvestigator" type="{Alma/ObsPrep/ObsProposal}InvestigatorT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ProposalFeedback" type="{Alma/ObsPrep/ObsProposal}ProposalFeedbackT"/>
 *       &lt;/sequence>
 *       &lt;attribute name="schemaVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="13" />
 *       &lt;attribute name="revision" type="{http://www.w3.org/2001/XMLSchema}string" default="24" />
 *       &lt;attribute name="almatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="APDM::ObsProposal" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObsProposal", namespace = "Alma/ObsPrep/ObsProposal", propOrder = {
    "obsProposalEntity",
    "documentsRef",
    "obsProjectRef",
    "title",
    "code",
    "_abstract",
    "relatedProposals",
    "previousProposals",
    "dateReceived",
    "cycle",
    "studentProject",
    "continuation",
    "recentPublications",
    "scientificCategoryCode",
    "proposalTypeCode",
    "scientificCategoryString",
    "proposalTypeString",
    "keyword",
    "keywordCode",
    "resubmittedProjectCode",
    "isResubmission",
    "duplicateObservationsJustification",
    "principalInvestigator",
    "coInvestigator",
    "coPrincipalInvestigator",
    "proposalFeedback"
})
@XmlRootElement
@JsonIgnoreProperties(ignoreUnknown = true)
public class ObsProposal
    extends ObsPhaseT
{

    @XmlElement(name = "ObsProposalEntity", required = true)
    private ObsProposalEntityT obsProposalEntity;
    @XmlElement(name = "DocumentsRef")
    private ObsAttachmentRefT documentsRef;
    @XmlElement(name = "ObsProjectRef", required = true)
    private ObsProjectRefT obsProjectRef;
    @XmlElement(required = true)
    private String title;
    @XmlElement(required = true)
    private String code;
    @XmlElement(name = "abstract", required = true)
    private String _abstract;
    @XmlElement(required = true)
    private String relatedProposals;
    @XmlElement(required = true)
    private String previousProposals;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    private String dateReceived;
    @XmlElement(required = true)
    private String cycle;
    @XmlElement(defaultValue = "false")
    private boolean studentProject;
    @XmlElement(defaultValue = "false")
    private boolean continuation;
    @XmlElement(required = true)
    private String recentPublications;
    @XmlElement(required = true, defaultValue = "10")
    private String scientificCategoryCode;
    @XmlElement(required = true, defaultValue = "S")
    private String proposalTypeCode;
    @XmlElement(required = true)
    private String scientificCategoryString;
    @XmlElement(required = true)
    private String proposalTypeString;
    private List<String> keyword;
    private List<String> keywordCode;
    private String resubmittedProjectCode;
    @XmlElement(defaultValue = "false")
    private Boolean isResubmission;
    private String duplicateObservationsJustification;
    @XmlElement(name = "PrincipalInvestigator", required = true)
    private InvestigatorT principalInvestigator;
    @XmlElement(name = "CoInvestigator")
    private List<InvestigatorT> coInvestigator;
    @XmlElement(name = "CoPrincipalInvestigator")
    private List<InvestigatorT> coPrincipalInvestigator;
    @XmlElement(name = "ProposalFeedback", required = true)
    private ProposalFeedbackT proposalFeedback;
    @XmlAttribute(name = "schemaVersion", required = true)
    private String schemaVersion;
    @XmlAttribute(name = "revision")
    private String revision;
    @XmlAttribute(name = "almatype", required = true)
    private String almatype;

    public ObsProposal() {
        this.setObsProposalEntity(new ObsProposalEntityT());
    }

    public void setObsProject(ObsProject project) {
        this.setObsProjectRef(ObsProjectRefT.createFromProject(project));
    }

    /**
     * Gets the value of the obsProposalEntity property.
     * 
     * @return
     *     possible object is
     *     {@link ObsProposalEntityT }
     *     
     */
    public ObsProposalEntityT getObsProposalEntity() {
        return obsProposalEntity;
    }

    /**
     * Sets the value of the obsProposalEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObsProposalEntityT }
     *     
     */
    public void setObsProposalEntity(ObsProposalEntityT value) {
        this.obsProposalEntity = value;
    }

    /**
     * Gets the value of the documentsRef property.
     * 
     * @return
     *     possible object is
     *     {@link ObsAttachmentRefT }
     *     
     */
    public ObsAttachmentRefT getDocumentsRef() {
        return documentsRef;
    }

    /**
     * Sets the value of the documentsRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObsAttachmentRefT }
     *     
     */
    public void setDocumentsRef(ObsAttachmentRefT value) {
        this.documentsRef = value;
    }

    /**
     * Gets the value of the obsProjectRef property.
     * 
     * @return
     *     possible object is
     *     {@link ObsProjectRefT }
     *     
     */
    public ObsProjectRefT getObsProjectRef() {
        return obsProjectRef;
    }

    /**
     * Sets the value of the obsProjectRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObsProjectRefT }
     *     
     */
    public void setObsProjectRef(ObsProjectRefT value) {
        this.obsProjectRef = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbstract(String value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the relatedProposals property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedProposals() {
        return relatedProposals;
    }

    /**
     * Sets the value of the relatedProposals property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedProposals(String value) {
        this.relatedProposals = value;
    }

    /**
     * Gets the value of the previousProposals property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousProposals() {
        return previousProposals;
    }

    /**
     * Sets the value of the previousProposals property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousProposals(String value) {
        this.previousProposals = value;
    }

    /**
     * Gets the value of the dateReceived property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getDateReceived() {
        return dateReceived;
    }

    /**
     * Sets the value of the dateReceived property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateReceived(String value) {
        this.dateReceived = value;
    }

    /**
     * Gets the value of the cycle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCycle() {
        return cycle;
    }

    /**
     * Sets the value of the cycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCycle(String value) {
        this.cycle = value;
    }

    /**
     * Gets the value of the studentProject property.
     * 
     */
    public boolean isStudentProject() {
        return studentProject;
    }

    /**
     * Sets the value of the studentProject property.
     * 
     */
    public void setStudentProject(boolean value) {
        this.studentProject = value;
    }

    /**
     * Gets the value of the continuation property.
     * 
     */
    public boolean isContinuation() {
        return continuation;
    }

    /**
     * Sets the value of the continuation property.
     * 
     */
    public void setContinuation(boolean value) {
        this.continuation = value;
    }

    /**
     * Gets the value of the recentPublications property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecentPublications() {
        return recentPublications;
    }

    /**
     * Sets the value of the recentPublications property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecentPublications(String value) {
        this.recentPublications = value;
    }

    /**
     * Gets the value of the scientificCategoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScientificCategoryCode() {
        return scientificCategoryCode;
    }

    /**
     * Sets the value of the scientificCategoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScientificCategoryCode(String value) {
        this.scientificCategoryCode = value;
    }

    /**
     * Gets the value of the proposalTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProposalTypeCode() {
        return proposalTypeCode;
    }

    /**
     * Sets the value of the proposalTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProposalTypeCode(String value) {
        this.proposalTypeCode = value;
    }

    /**
     * Gets the value of the scientificCategoryString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScientificCategoryString() {
        return scientificCategoryString;
    }

    /**
     * Sets the value of the scientificCategoryString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScientificCategoryString(String value) {
        this.scientificCategoryString = value;
    }

    /**
     * Gets the value of the proposalTypeString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProposalTypeString() {
        return proposalTypeString;
    }

    /**
     * Sets the value of the proposalTypeString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProposalTypeString(String value) {
        this.proposalTypeString = value;
    }

    /**
     * Gets the value of the keyword property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyword property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeyword().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getKeyword() {
        if (keyword == null) {
            keyword = new ArrayList<>();
        }
        return this.keyword;
    }

    /**
     * Gets the value of the keywordCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keywordCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeywordCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getKeywordCode() {
        if (keywordCode == null) {
            keywordCode = new ArrayList<>();
        }
        return this.keywordCode;
    }

    /**
     * Gets the value of the resubmittedProjectCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResubmittedProjectCode() {
        return resubmittedProjectCode;
    }

    /**
     * Sets the value of the resubmittedProjectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResubmittedProjectCode(String value) {
        this.resubmittedProjectCode = value;
    }

    /**
     * Gets the value of the isResubmission property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsResubmission() {
        return isResubmission;
    }

    /**
     * Sets the value of the isResubmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsResubmission(Boolean value) {
        this.isResubmission = value;
    }

    /**
     * Gets the value of the duplicateObservationsJustification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuplicateObservationsJustification() {
        return duplicateObservationsJustification;
    }

    /**
     * Sets the value of the duplicateObservationsJustification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuplicateObservationsJustification(String value) {
        this.duplicateObservationsJustification = value;
    }

    /**
     * Gets the value of the principalInvestigator property.
     * 
     * @return
     *     possible object is
     *     {@link InvestigatorT }
     *     
     */
    public InvestigatorT getPrincipalInvestigator() {
        return principalInvestigator;
    }

    /**
     * Sets the value of the principalInvestigator property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvestigatorT }
     *     
     */
    public void setPrincipalInvestigator(InvestigatorT value) {
        this.principalInvestigator = value;
    }

    /**
     * Gets the value of the coInvestigator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coInvestigator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoInvestigator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvestigatorT }
     * 
     * 
     */
    public List<InvestigatorT> getCoInvestigator() {
        if (coInvestigator == null) {
            coInvestigator = new ArrayList<>();
        }
        return this.coInvestigator;
    }

    /**
     * Gets the value of the coPrincipalInvestigator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coPrincipalInvestigator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoPrincipalInvestigator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvestigatorT }
     * 
     * 
     */
    public List<InvestigatorT> getCoPrincipalInvestigator() {
        if (coPrincipalInvestigator == null) {
            coPrincipalInvestigator = new ArrayList<>();
        }
        return this.coPrincipalInvestigator;
    }

    /**
     * Gets the value of the proposalFeedback property.
     * 
     * @return
     *     possible object is
     *     {@link ProposalFeedbackT }
     *     
     */
    public ProposalFeedbackT getProposalFeedback() {
        return proposalFeedback;
    }

    /**
     * Sets the value of the proposalFeedback property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProposalFeedbackT }
     *     
     */
    public void setProposalFeedback(ProposalFeedbackT value) {
        this.proposalFeedback = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        if (schemaVersion == null) {
            return "13";
        } else {
            return schemaVersion;
        }
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevision() {
        if (revision == null) {
            return "24";
        } else {
            return revision;
        }
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevision(String value) {
        this.revision = value;
    }

    /**
     * Gets the value of the almatype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlmatype() {
        if (almatype == null) {
            return "APDM::ObsProposal";
        } else {
            return almatype;
        }
    }

    /**
     * Sets the value of the almatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlmatype(String value) {
        this.almatype = value;
    }

}
