//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObsUnitStatusT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObsUnitStatusT">
 *   &lt;complexContent>
 *     &lt;extension base="{Alma/Scheduling/ProjectStatus}StatusBaseT">
 *       &lt;sequence>
 *         &lt;element name="ObsUnitSetMemberType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TotalRequiredTimeInSec" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TotalUsedTimeInSec" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ContainingObsUnitSetRef" type="{Alma/Scheduling/OUSStatus}OUSStatusRefT"/>
 *         &lt;element name="ProjectStatusRef" type="{Alma/Scheduling/ProjectStatus}ProjectStatusRefT"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObsUnitStatusT", namespace = "Alma/Scheduling/ProjectStatus", propOrder = {
    "obsUnitSetMemberType",
    "totalRequiredTimeInSec",
    "totalUsedTimeInSec",
    "containingObsUnitSetRef",
    "projectStatusRef"
})
@XmlSeeAlso({
    SBStatus.class,
    OUSStatus.class
})
public abstract class ObsUnitStatusT
    extends StatusBaseT
{

    @XmlElement(name = "ObsUnitSetMemberType", required = true)
    protected String obsUnitSetMemberType;
    @XmlElement(name = "TotalRequiredTimeInSec")
    protected int totalRequiredTimeInSec;
    @XmlElement(name = "TotalUsedTimeInSec")
    protected int totalUsedTimeInSec;
    @XmlElement(name = "ContainingObsUnitSetRef", required = true)
    protected OUSStatusRefT containingObsUnitSetRef;
    @XmlElement(name = "ProjectStatusRef", required = true)
    protected ProjectStatusRefT projectStatusRef;

    /**
     * Gets the value of the obsUnitSetMemberType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObsUnitSetMemberType() {
        return obsUnitSetMemberType;
    }

    /**
     * Sets the value of the obsUnitSetMemberType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObsUnitSetMemberType(String value) {
        this.obsUnitSetMemberType = value;
    }

    /**
     * Gets the value of the totalRequiredTimeInSec property.
     * 
     */
    public int getTotalRequiredTimeInSec() {
        return totalRequiredTimeInSec;
    }

    /**
     * Sets the value of the totalRequiredTimeInSec property.
     * 
     */
    public void setTotalRequiredTimeInSec(int value) {
        this.totalRequiredTimeInSec = value;
    }

    /**
     * Gets the value of the totalUsedTimeInSec property.
     * 
     */
    public int getTotalUsedTimeInSec() {
        return totalUsedTimeInSec;
    }

    /**
     * Sets the value of the totalUsedTimeInSec property.
     * 
     */
    public void setTotalUsedTimeInSec(int value) {
        this.totalUsedTimeInSec = value;
    }

    /**
     * Gets the value of the containingObsUnitSetRef property.
     * 
     * @return
     *     possible object is
     *     {@link OUSStatusRefT }
     *     
     */
    public OUSStatusRefT getContainingObsUnitSetRef() {
        return containingObsUnitSetRef;
    }

    /**
     * Sets the value of the containingObsUnitSetRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link OUSStatusRefT }
     *     
     */
    public void setContainingObsUnitSetRef(OUSStatusRefT value) {
        this.containingObsUnitSetRef = value;
    }

    /**
     * Gets the value of the projectStatusRef property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectStatusRefT }
     *     
     */
    public ProjectStatusRefT getProjectStatusRef() {
        return projectStatusRef;
    }

    /**
     * Sets the value of the projectStatusRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectStatusRefT }
     *     
     */
    public void setProjectStatusRef(ProjectStatusRefT value) {
        this.projectStatusRef = value;
    }

}
