/*
 * ALMA - Atacama Large Millimeter Array
 * Copyright (c) UKATC - UK Astronomy Technology Centre, Science and Technology Facilities Council, 2018
 * (in the framework of the ALMA collaboration).
 * All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A specialisation of ObsUnit that holds a collection of ObsUnits, This allows the creation of arbitrary structures, and also forms the container for SchedBlocks. Attributes allow the definition of data processing scripts that will occur at specific levels in the hierarchy. Note that the "top level" ObsUnitSet within an Observing Phase has a role name of "ObsPlan". This is to indicate that it describes the actual observing plan, described in the ALMA "system view" intended executed at the observatory. (For PhaseI this ObsPlan, if it is detailed, is still to be confirmed and will never get executed. For Phase II it is what was approved and must be detailed and valid as it contains what will be executed).
 * 
 * <p>Java class for ObsUnitSetT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObsUnitSetT">
 *   &lt;complexContent>
 *     &lt;extension base="{Alma/ObsPrep/ObsProject}ObsUnitT">
 *       &lt;sequence>
 *         &lt;element name="scienceProcessingScript" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="runSciencePipeline" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="DataProcessingParameters" type="{Alma/ObsPrep/ObsProject}DataProcessingParametersT"/>
 *         &lt;element name="FlowControl" type="{Alma/ObsPrep/ObsProject}FlowControlT"/>
 *         &lt;choice>
 *           &lt;element name="ObsUnitSet" type="{Alma/ObsPrep/ObsProject}ObsUnitSetT" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="SchedBlockRef" type="{Alma/ObsPrep/SchedBlock}SchedBlockRefT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="OUSStatusRef" type="{Alma/Scheduling/OUSStatus}OUSStatusRefT"/>
 *       &lt;/sequence>
 *       &lt;attribute name="entityPartId" type="{Alma/CommonEntity}EntityPartIdT" />
 *       &lt;attribute name="almatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="APDM::ObsUnitSet" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObsUnitSetT", namespace = "Alma/ObsPrep/ObsProject", propOrder = {
    "scienceProcessingScript",
    "runSciencePipeline",
    "dataProcessingParameters",
    "flowControl",
    "obsUnitSet",
    "schedBlockRef",
    "ousStatusRef"
})
public class ObsUnitSetT
    extends ObsUnitT
{

    @XmlElement(required = true)
    private String scienceProcessingScript;
    @XmlElement(defaultValue = "false")
    private boolean runSciencePipeline;
    @XmlElement(name = "DataProcessingParameters", required = true)
    private DataProcessingParametersT dataProcessingParameters;
    @XmlElement(name = "FlowControl", required = true)
    private FlowControlT flowControl;
    @XmlElement(name = "ObsUnitSet")
    private List<ObsUnitSetT> obsUnitSet;
    @XmlElement(name = "SchedBlockRef")
    private List<SchedBlockRefT> schedBlockRef;
    @XmlElement(name = "OUSStatusRef", required = true)
    private OUSStatusRefT ousStatusRef;
    @XmlAttribute(name = "entityPartId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    private String entityPartId;
    @XmlAttribute(name = "almatype", required = true)
    private String almatype;

    /**
     * Gets the value of the scienceProcessingScript property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScienceProcessingScript() {
        return scienceProcessingScript;
    }

    /**
     * Sets the value of the scienceProcessingScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScienceProcessingScript(String value) {
        this.scienceProcessingScript = value;
    }

    /**
     * Gets the value of the runSciencePipeline property.
     * 
     */
    public boolean isRunSciencePipeline() {
        return runSciencePipeline;
    }

    /**
     * Sets the value of the runSciencePipeline property.
     * 
     */
    public void setRunSciencePipeline(boolean value) {
        this.runSciencePipeline = value;
    }

    /**
     * Gets the value of the dataProcessingParameters property.
     * 
     * @return
     *     possible object is
     *     {@link DataProcessingParametersT }
     *     
     */
    public DataProcessingParametersT getDataProcessingParameters() {
        return dataProcessingParameters;
    }

    /**
     * Sets the value of the dataProcessingParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataProcessingParametersT }
     *     
     */
    public void setDataProcessingParameters(DataProcessingParametersT value) {
        this.dataProcessingParameters = value;
    }

    /**
     * Gets the value of the flowControl property.
     * 
     * @return
     *     possible object is
     *     {@link FlowControlT }
     *     
     */
    public FlowControlT getFlowControl() {
        return flowControl;
    }

    /**
     * Sets the value of the flowControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlowControlT }
     *     
     */
    public void setFlowControl(FlowControlT value) {
        this.flowControl = value;
    }

    /**
     * Gets the value of the obsUnitSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the obsUnitSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObsUnitSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObsUnitSetT }
     * 
     * 
     */
    public List<ObsUnitSetT> getObsUnitSet() {
        if (obsUnitSet == null) {
            obsUnitSet = new ArrayList<>();
        }
        return this.obsUnitSet;
    }

    /**
     * Gets the value of the schedBlockRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the schedBlockRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSchedBlockRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SchedBlockRefT }
     * 
     * 
     */
    public List<SchedBlockRefT> getSchedBlockRef() {
        if (schedBlockRef == null) {
            schedBlockRef = new ArrayList<>();
        }
        return this.schedBlockRef;
    }

    /**
     * Gets the value of the ousStatusRef property.
     * 
     * @return
     *     possible object is
     *     {@link OUSStatusRefT }
     *     
     */
    public OUSStatusRefT getOUSStatusRef() {
        return ousStatusRef;
    }

    /**
     * Sets the value of the ousStatusRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link OUSStatusRefT }
     *     
     */
    public void setOUSStatusRef(OUSStatusRefT value) {
        this.ousStatusRef = value;
    }

    /**
     * Gets the value of the entityPartId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityPartId() {
        return entityPartId;
    }

    /**
     * Sets the value of the entityPartId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityPartId(String value) {
        this.entityPartId = value;
    }

    /**
     * Gets the value of the almatype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlmatype() {
        if (almatype == null) {
            return "APDM::ObsUnitSet";
        } else {
            return almatype;
        }
    }

    /**
     * Sets the value of the almatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlmatype(String value) {
        this.almatype = value;
    }

}
