/*
 * ALMA - Atacama Large Millimeter Array
 * Copyright (c) UKATC - UK Astronomy Technology Centre, Science and Technology Facilities Council, 2018
 * (in the framework of the ALMA collaboration).
 * All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Query parameters used to query a catalog of potential optical pointing sources
 * 
 * <p>Java class for OpticalPointingTargetQueryParametersT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OpticalPointingTargetQueryParametersT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="minCoordinates" type="{Alma/ValueTypes}SkyCoordinatesT"/>
 *         &lt;element name="maxCoordinates" type="{Alma/ValueTypes}SkyCoordinatesT"/>
 *         &lt;element name="minMagnitude" type="{Alma/ValueTypes}MagnitudeT"/>
 *         &lt;element name="maxMagnitude" type="{Alma/ValueTypes}MagnitudeT"/>
 *         &lt;element name="minElevation" type="{Alma/ValueTypes}AngleT"/>
 *         &lt;element name="maxElevation" type="{Alma/ValueTypes}AngleT"/>
 *         &lt;element name="minAzimuth" type="{Alma/ValueTypes}AngleT"/>
 *         &lt;element name="maxAzimuth" type="{Alma/ValueTypes}AngleT"/>
 *         &lt;element name="lst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fieldMinSeparation" type="{Alma/ValueTypes}AngleT"/>
 *         &lt;element name="listMinSeparation" type="{Alma/ValueTypes}AngleT"/>
 *         &lt;element name="selectionFactor" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxTargets" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="catalogLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="localFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OpticalPointingTargetQueryParametersT", namespace = "Alma/ObsPrep/ObsProject", propOrder = {
    "minCoordinates",
    "maxCoordinates",
    "minMagnitude",
    "maxMagnitude",
    "minElevation",
    "maxElevation",
    "minAzimuth",
    "maxAzimuth",
    "lst",
    "fieldMinSeparation",
    "listMinSeparation",
    "selectionFactor",
    "maxTargets",
    "catalogLocation",
    "localFileName"
})
public class OpticalPointingTargetQueryParametersT {

    @XmlElement(required = true)
    private SkyCoordinatesT minCoordinates;
    @XmlElement(required = true)
    private SkyCoordinatesT maxCoordinates;
    @XmlElement(required = true)
    private MagnitudeT minMagnitude;
    @XmlElement(required = true)
    private MagnitudeT maxMagnitude;
    @XmlElement(required = true)
    private AngleT minElevation;
    @XmlElement(required = true)
    private AngleT maxElevation;
    @XmlElement(required = true)
    private AngleT minAzimuth;
    @XmlElement(required = true)
    private AngleT maxAzimuth;
    @XmlElement(required = true)
    private String lst;
    @XmlElement(required = true)
    private AngleT fieldMinSeparation;
    @XmlElement(required = true)
    private AngleT listMinSeparation;
    private int selectionFactor;
    private int maxTargets;
    @XmlElement(required = true)
    private String catalogLocation;
    @XmlElement(required = true)
    private String localFileName;

    /**
     * Gets the value of the minCoordinates property.
     * 
     * @return
     *     possible object is
     *     {@link SkyCoordinatesT }
     *     
     */
    public SkyCoordinatesT getMinCoordinates() {
        return minCoordinates;
    }

    /**
     * Sets the value of the minCoordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkyCoordinatesT }
     *     
     */
    public void setMinCoordinates(SkyCoordinatesT value) {
        this.minCoordinates = value;
    }

    /**
     * Gets the value of the maxCoordinates property.
     * 
     * @return
     *     possible object is
     *     {@link SkyCoordinatesT }
     *     
     */
    public SkyCoordinatesT getMaxCoordinates() {
        return maxCoordinates;
    }

    /**
     * Sets the value of the maxCoordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkyCoordinatesT }
     *     
     */
    public void setMaxCoordinates(SkyCoordinatesT value) {
        this.maxCoordinates = value;
    }

    /**
     * Gets the value of the minMagnitude property.
     * 
     * @return
     *     possible object is
     *     {@link MagnitudeT }
     *     
     */
    public MagnitudeT getMinMagnitude() {
        return minMagnitude;
    }

    /**
     * Sets the value of the minMagnitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link MagnitudeT }
     *     
     */
    public void setMinMagnitude(MagnitudeT value) {
        this.minMagnitude = value;
    }

    /**
     * Gets the value of the maxMagnitude property.
     * 
     * @return
     *     possible object is
     *     {@link MagnitudeT }
     *     
     */
    public MagnitudeT getMaxMagnitude() {
        return maxMagnitude;
    }

    /**
     * Sets the value of the maxMagnitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link MagnitudeT }
     *     
     */
    public void setMaxMagnitude(MagnitudeT value) {
        this.maxMagnitude = value;
    }

    /**
     * Gets the value of the minElevation property.
     * 
     * @return
     *     possible object is
     *     {@link AngleT }
     *     
     */
    public AngleT getMinElevation() {
        return minElevation;
    }

    /**
     * Sets the value of the minElevation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleT }
     *     
     */
    public void setMinElevation(AngleT value) {
        this.minElevation = value;
    }

    /**
     * Gets the value of the maxElevation property.
     * 
     * @return
     *     possible object is
     *     {@link AngleT }
     *     
     */
    public AngleT getMaxElevation() {
        return maxElevation;
    }

    /**
     * Sets the value of the maxElevation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleT }
     *     
     */
    public void setMaxElevation(AngleT value) {
        this.maxElevation = value;
    }

    /**
     * Gets the value of the minAzimuth property.
     * 
     * @return
     *     possible object is
     *     {@link AngleT }
     *     
     */
    public AngleT getMinAzimuth() {
        return minAzimuth;
    }

    /**
     * Sets the value of the minAzimuth property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleT }
     *     
     */
    public void setMinAzimuth(AngleT value) {
        this.minAzimuth = value;
    }

    /**
     * Gets the value of the maxAzimuth property.
     * 
     * @return
     *     possible object is
     *     {@link AngleT }
     *     
     */
    public AngleT getMaxAzimuth() {
        return maxAzimuth;
    }

    /**
     * Sets the value of the maxAzimuth property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleT }
     *     
     */
    public void setMaxAzimuth(AngleT value) {
        this.maxAzimuth = value;
    }

    /**
     * Gets the value of the lst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLst() {
        return lst;
    }

    /**
     * Sets the value of the lst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLst(String value) {
        this.lst = value;
    }

    /**
     * Gets the value of the fieldMinSeparation property.
     * 
     * @return
     *     possible object is
     *     {@link AngleT }
     *     
     */
    public AngleT getFieldMinSeparation() {
        return fieldMinSeparation;
    }

    /**
     * Sets the value of the fieldMinSeparation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleT }
     *     
     */
    public void setFieldMinSeparation(AngleT value) {
        this.fieldMinSeparation = value;
    }

    /**
     * Gets the value of the listMinSeparation property.
     * 
     * @return
     *     possible object is
     *     {@link AngleT }
     *     
     */
    public AngleT getListMinSeparation() {
        return listMinSeparation;
    }

    /**
     * Sets the value of the listMinSeparation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleT }
     *     
     */
    public void setListMinSeparation(AngleT value) {
        this.listMinSeparation = value;
    }

    /**
     * Gets the value of the selectionFactor property.
     * 
     */
    public int getSelectionFactor() {
        return selectionFactor;
    }

    /**
     * Sets the value of the selectionFactor property.
     * 
     */
    public void setSelectionFactor(int value) {
        this.selectionFactor = value;
    }

    /**
     * Gets the value of the maxTargets property.
     * 
     */
    public int getMaxTargets() {
        return maxTargets;
    }

    /**
     * Sets the value of the maxTargets property.
     * 
     */
    public void setMaxTargets(int value) {
        this.maxTargets = value;
    }

    /**
     * Gets the value of the catalogLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogLocation() {
        return catalogLocation;
    }

    /**
     * Sets the value of the catalogLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogLocation(String value) {
        this.catalogLocation = value;
    }

    /**
     * Gets the value of the localFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalFileName() {
        return localFileName;
    }

    /**
     * Sets the value of the localFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalFileName(String value) {
        this.localFileName = value;
    }

}
