/*
 * ALMA - Atacama Large Millimeter Array
 * Copyright (c) UKATC - UK Astronomy Technology Centre, Science and Technology Facilities Council, 2018
 * (in the framework of the ALMA collaboration).
 * All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies the conditions that must be met before this SchedBlock can be executed.
 * 
 * <p>Java class for PreconditionsT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreconditionsT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="baselineCalValid" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="polarizationCalValid" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="minAllowedHA" type="{Alma/ValueTypes}UserAngleT"/>
 *         &lt;element name="maxAllowedHA" type="{Alma/ValueTypes}UserAngleT"/>
 *         &lt;element name="WeatherConstraints" type="{Alma/ObsPrep/ObsProject}WeatherConstraintsT"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreconditionsT", namespace = "Alma/ObsPrep/ObsProject", propOrder = {
    "baselineCalValid",
    "polarizationCalValid",
    "minAllowedHA",
    "maxAllowedHA",
    "weatherConstraints"
})
public class PreconditionsT {

    @XmlElement(defaultValue = "false")
    private boolean baselineCalValid;
    @XmlElement(defaultValue = "false")
    private boolean polarizationCalValid;
    @XmlElement(required = true)
    private UserAngleT minAllowedHA;
    @XmlElement(required = true)
    private UserAngleT maxAllowedHA;
    @XmlElement(name = "WeatherConstraints", required = true)
    private WeatherConstraintsT weatherConstraints;

    /**
     * Gets the value of the baselineCalValid property.
     * 
     */
    public boolean isBaselineCalValid() {
        return baselineCalValid;
    }

    /**
     * Sets the value of the baselineCalValid property.
     * 
     */
    public void setBaselineCalValid(boolean value) {
        this.baselineCalValid = value;
    }

    /**
     * Gets the value of the polarizationCalValid property.
     * 
     */
    public boolean isPolarizationCalValid() {
        return polarizationCalValid;
    }

    /**
     * Sets the value of the polarizationCalValid property.
     * 
     */
    public void setPolarizationCalValid(boolean value) {
        this.polarizationCalValid = value;
    }

    /**
     * Gets the value of the minAllowedHA property.
     * 
     * @return
     *     possible object is
     *     {@link UserAngleT }
     *     
     */
    public UserAngleT getMinAllowedHA() {
        return minAllowedHA;
    }

    /**
     * Sets the value of the minAllowedHA property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAngleT }
     *     
     */
    public void setMinAllowedHA(UserAngleT value) {
        this.minAllowedHA = value;
    }

    /**
     * Gets the value of the maxAllowedHA property.
     * 
     * @return
     *     possible object is
     *     {@link UserAngleT }
     *     
     */
    public UserAngleT getMaxAllowedHA() {
        return maxAllowedHA;
    }

    /**
     * Sets the value of the maxAllowedHA property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAngleT }
     *     
     */
    public void setMaxAllowedHA(UserAngleT value) {
        this.maxAllowedHA = value;
    }

    /**
     * Gets the value of the weatherConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link WeatherConstraintsT }
     *     
     */
    public WeatherConstraintsT getWeatherConstraints() {
        return weatherConstraints;
    }

    /**
     * Sets the value of the weatherConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeatherConstraintsT }
     *     
     */
    public void setWeatherConstraints(WeatherConstraintsT value) {
        this.weatherConstraints = value;
    }

}
