//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A QuerySource is a special type of FieldSource which does does specify directly a single source to point at. Instead it specifies a query that should be executed by the Control system to obtain a set of results matching that query. These results are turned into FieldSources, up to the maximum number desired.
 * 
 * <p>Java class for QuerySourceT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuerySourceT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="queryCenter" type="{Alma/ValueTypes}SkyCoordinatesT"/>
 *         &lt;element name="searchRadius" type="{Alma/ValueTypes}AngleT"/>
 *         &lt;element name="minFrequency" type="{Alma/ValueTypes}FrequencyT"/>
 *         &lt;element name="maxFrequency" type="{Alma/ValueTypes}FrequencyT"/>
 *         &lt;element name="minFlux" type="{Alma/ValueTypes}FluxT"/>
 *         &lt;element name="maxFlux" type="{Alma/ValueTypes}FluxT"/>
 *         &lt;element name="minTimeSinceObserved" type="{Alma/ValueTypes}TimeT"/>
 *         &lt;element name="maxTimeSinceObserved" type="{Alma/ValueTypes}TimeT"/>
 *         &lt;element name="use" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="maxSources" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *       &lt;attribute name="intendedUse" default="Phase">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Amplitude"/>
 *             &lt;enumeration value="Atmospheric"/>
 *             &lt;enumeration value="Bandpass"/>
 *             &lt;enumeration value="Phase"/>
 *             &lt;enumeration value="Pointing"/>
 *             &lt;enumeration value="Focus"/>
 *             &lt;enumeration value="Polarization"/>
 *             &lt;enumeration value="Delay"/>
 *             &lt;enumeration value="SidebandRatio"/>
 *             &lt;enumeration value="CheckSource"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuerySourceT", propOrder = {
    "queryCenter",
    "searchRadius",
    "minFrequency",
    "maxFrequency",
    "minFlux",
    "maxFlux",
    "minTimeSinceObserved",
    "maxTimeSinceObserved",
    "use",
    "maxSources"
})
public class QuerySourceT {

    @XmlElement(required = true)
    protected SkyCoordinatesT queryCenter;
    @XmlElement(required = true)
    protected AngleT searchRadius;
    @XmlElement(required = true)
    protected FrequencyT minFrequency;
    @XmlElement(required = true)
    protected FrequencyT maxFrequency;
    @XmlElement(required = true)
    protected FluxT minFlux;
    @XmlElement(required = true)
    protected FluxT maxFlux;
    @XmlElement(required = true)
    protected TimeT minTimeSinceObserved;
    @XmlElement(required = true)
    protected TimeT maxTimeSinceObserved;
    @XmlElement(required = true)
    protected String use;
    @XmlElement(defaultValue = "1")
    protected int maxSources;
    @XmlAttribute(name = "intendedUse")
    protected String intendedUse;

    /**
     * Gets the value of the queryCenter property.
     * 
     * @return
     *     possible object is
     *     {@link SkyCoordinatesT }
     *     
     */
    public SkyCoordinatesT getQueryCenter() {
        return queryCenter;
    }

    /**
     * Sets the value of the queryCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkyCoordinatesT }
     *     
     */
    public void setQueryCenter(SkyCoordinatesT value) {
        this.queryCenter = value;
    }

    /**
     * Gets the value of the searchRadius property.
     * 
     * @return
     *     possible object is
     *     {@link AngleT }
     *     
     */
    public AngleT getSearchRadius() {
        return searchRadius;
    }

    /**
     * Sets the value of the searchRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleT }
     *     
     */
    public void setSearchRadius(AngleT value) {
        this.searchRadius = value;
    }

    /**
     * Gets the value of the minFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link FrequencyT }
     *     
     */
    public FrequencyT getMinFrequency() {
        return minFrequency;
    }

    /**
     * Sets the value of the minFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrequencyT }
     *     
     */
    public void setMinFrequency(FrequencyT value) {
        this.minFrequency = value;
    }

    /**
     * Gets the value of the maxFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link FrequencyT }
     *     
     */
    public FrequencyT getMaxFrequency() {
        return maxFrequency;
    }

    /**
     * Sets the value of the maxFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrequencyT }
     *     
     */
    public void setMaxFrequency(FrequencyT value) {
        this.maxFrequency = value;
    }

    /**
     * Gets the value of the minFlux property.
     * 
     * @return
     *     possible object is
     *     {@link FluxT }
     *     
     */
    public FluxT getMinFlux() {
        return minFlux;
    }

    /**
     * Sets the value of the minFlux property.
     * 
     * @param value
     *     allowed object is
     *     {@link FluxT }
     *     
     */
    public void setMinFlux(FluxT value) {
        this.minFlux = value;
    }

    /**
     * Gets the value of the maxFlux property.
     * 
     * @return
     *     possible object is
     *     {@link FluxT }
     *     
     */
    public FluxT getMaxFlux() {
        return maxFlux;
    }

    /**
     * Sets the value of the maxFlux property.
     * 
     * @param value
     *     allowed object is
     *     {@link FluxT }
     *     
     */
    public void setMaxFlux(FluxT value) {
        this.maxFlux = value;
    }

    /**
     * Gets the value of the minTimeSinceObserved property.
     * 
     * @return
     *     possible object is
     *     {@link TimeT }
     *     
     */
    public TimeT getMinTimeSinceObserved() {
        return minTimeSinceObserved;
    }

    /**
     * Sets the value of the minTimeSinceObserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeT }
     *     
     */
    public void setMinTimeSinceObserved(TimeT value) {
        this.minTimeSinceObserved = value;
    }

    /**
     * Gets the value of the maxTimeSinceObserved property.
     * 
     * @return
     *     possible object is
     *     {@link TimeT }
     *     
     */
    public TimeT getMaxTimeSinceObserved() {
        return maxTimeSinceObserved;
    }

    /**
     * Sets the value of the maxTimeSinceObserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeT }
     *     
     */
    public void setMaxTimeSinceObserved(TimeT value) {
        this.maxTimeSinceObserved = value;
    }

    /**
     * Gets the value of the use property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUse() {
        return use;
    }

    /**
     * Sets the value of the use property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUse(String value) {
        this.use = value;
    }

    /**
     * Gets the value of the maxSources property.
     * 
     */
    public int getMaxSources() {
        return maxSources;
    }

    /**
     * Sets the value of the maxSources property.
     * 
     */
    public void setMaxSources(int value) {
        this.maxSources = value;
    }

    /**
     * Gets the value of the intendedUse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntendedUse() {
        if (intendedUse == null) {
            return "Phase";
        } else {
            return intendedUse;
        }
    }

    /**
     * Sets the value of the intendedUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntendedUse(String value) {
        this.intendedUse = value;
    }

}
