//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model.obsproposal;

import com.prototype.ot.microservices.projectservice.model.TimeT;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The time required in the proposal for a given receiver band.
 * 
 * <p>Java class for ReceiverTimeT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReceiverTimeT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="time" type="{Alma/ValueTypes}TimeT"/>
 *       &lt;/sequence>
 *       &lt;attribute name="receiverBand">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="ALMA_RB_01"/>
 *             &lt;enumeration value="ALMA_RB_02"/>
 *             &lt;enumeration value="ALMA_RB_03"/>
 *             &lt;enumeration value="ALMA_RB_04"/>
 *             &lt;enumeration value="ALMA_RB_05"/>
 *             &lt;enumeration value="ALMA_RB_06"/>
 *             &lt;enumeration value="ALMA_RB_07"/>
 *             &lt;enumeration value="ALMA_RB_08"/>
 *             &lt;enumeration value="ALMA_RB_09"/>
 *             &lt;enumeration value="ALMA_RB_10"/>
 *             &lt;enumeration value="UNDEFINED"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReceiverTimeT", namespace = "Alma/ObsPrep/ObsProposal", propOrder = {
    "time"
})
public class ReceiverTimeT {

    @XmlElement(required = true)
    protected TimeT time;
    @XmlAttribute(name = "receiverBand")
    protected String receiverBand;

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link TimeT }
     *     
     */
    public TimeT getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeT }
     *     
     */
    public void setTime(TimeT value) {
        this.time = value;
    }

    /**
     * Gets the value of the receiverBand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverBand() {
        return receiverBand;
    }

    /**
     * Sets the value of the receiverBand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverBand(String value) {
        this.receiverBand = value;
    }

}
