/*
 * ALMA - Atacama Large Millimeter Array
 * Copyright (c) UKATC - UK Astronomy Technology Centre, Science and Technology Facilities Council, 2018
 * (in the framework of the ALMA collaboration).
 * All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SchedBlock complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SchedBlock">
 *   &lt;complexContent>
 *     &lt;extension base="{Alma/ObsPrep/ObsProject}ObsUnitT">
 *       &lt;sequence>
 *         &lt;element name="SchedBlockEntity" type="{Alma/ObsPrep/SchedBlock}SchedBlockEntityT"/>
 *         &lt;element name="SBStatusRef" type="{Alma/Scheduling/SBStatus}SBStatusRefT"/>
 *         &lt;element name="ObsUnitSetRef" type="{Alma/ObsPrep/ObsProject}ObsProjectRefT" minOccurs="0"/>
 *         &lt;element name="standardMode" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="modeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pIName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="expertParameter" type="{Alma/ValueTypes}KeywordValueT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="qa0Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="OpticalCameraSpec" type="{Alma/ObsPrep/SchedBlock}OpticalCameraSpecT" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="SpectralSpec" type="{Alma/ObsPrep/SchedBlock}SpectralSpecT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="FieldSource" type="{Alma/ObsPrep/SchedBlock}FieldSourceT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ObservingGroup" type="{Alma/ObsPrep/SchedBlock}ObservingGroupT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="AmplitudeCalParameters" type="{Alma/ObsPrep/SchedBlock}AmplitudeCalParametersT"/>
 *           &lt;element name="AtmosphericCalParameters" type="{Alma/ObsPrep/SchedBlock}AtmosphericCalParametersT"/>
 *           &lt;element name="BandpassCalParameters" type="{Alma/ObsPrep/SchedBlock}BandpassCalParametersT"/>
 *           &lt;element name="CheckSourceCalParameters" type="{Alma/ObsPrep/SchedBlock}CheckSourceCalParametersT"/>
 *           &lt;element name="DelayCalParameters" type="{Alma/ObsPrep/SchedBlock}DelayCalParametersT"/>
 *           &lt;element name="FocusCalParameters" type="{Alma/ObsPrep/SchedBlock}FocusCalParametersT"/>
 *           &lt;element name="HolographyParameters" type="{Alma/ObsPrep/SchedBlock}HolographyParametersT"/>
 *           &lt;element name="OpticalPointingParameters" type="{Alma/ObsPrep/SchedBlock}OpticalPointingParametersT"/>
 *           &lt;element name="PhaseCalParameters" type="{Alma/ObsPrep/SchedBlock}PhaseCalParametersT"/>
 *           &lt;element name="PointingCalParameters" type="{Alma/ObsPrep/SchedBlock}PointingCalParametersT"/>
 *           &lt;element name="PolarizationCalParameters" type="{Alma/ObsPrep/SchedBlock}PolarizationCalParametersT"/>
 *           &lt;element name="RadiometricPointingParameters" type="{Alma/ObsPrep/SchedBlock}RadiometricPointingParametersT"/>
 *           &lt;element name="ReservationParameters" type="{Alma/ObsPrep/SchedBlock}ReservationParametersT"/>
 *           &lt;element name="ScienceParameters" type="{Alma/ObsPrep/SchedBlock}ScienceParametersT"/>
 *           &lt;element name="SidebandRatioCalParameters" type="{Alma/ObsPrep/SchedBlock}SidebandRatioCalParametersT"/>
 *         &lt;/choice>
 *         &lt;element name="ObsProcedure" type="{Alma/ObsPrep/SchedBlock}ObsProcedureT"/>
 *         &lt;element name="Preconditions" type="{Alma/ObsPrep/ObsProject}PreconditionsT"/>
 *         &lt;element name="SchedBlockControl" type="{Alma/ObsPrep/SchedBlock}SchedBlockControlT"/>
 *         &lt;element name="SchedulingConstraints" type="{Alma/ObsPrep/SchedBlock}SchedulingConstraintsT"/>
 *         &lt;element name="Target" type="{Alma/ObsPrep/SchedBlock}TargetT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TemporalConstraints" type="{Alma/ObsPrep/SchedBlock}TemporalConstraintsT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TimeAllocationBreakdown" type="{Alma/ObsPrep/ObsProposal}TimeAllocationBreakdownT" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="schemaVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="13" />
 *       &lt;attribute name="revision" type="{http://www.w3.org/2001/XMLSchema}string" default="24" />
 *       &lt;attribute name="almatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="APDM::SchedBlock" />
 *       &lt;attribute name="modeType" default="User">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Observatory"/>
 *             &lt;enumeration value="User"/>
 *             &lt;enumeration value="Expert"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SchedBlock", propOrder = {
    "schedBlockEntity",
    "sbStatusRef",
    "obsUnitSetRef",
    "standardMode",
    "modeName",
    "piName",
    "expertParameter",
    "qa0Notes",
    "opticalCameraSpec",
    "spectralSpec",
    "fieldSource",
    "observingGroup",
    "amplitudeCalParametersOrAtmosphericCalParametersOrBandpassCalParameters",
    "obsProcedure",
    "preconditions",
    "schedBlockControl",
    "schedulingConstraints",
    "target",
    "temporalConstraints",
    "timeAllocationBreakdown"
})
public class SchedBlock
    extends ObsUnitT
{

    @XmlElement(name = "SchedBlockEntity", required = true)
    private SchedBlockEntityT schedBlockEntity;
    @XmlElement(name = "SBStatusRef", required = true)
    private SBStatusRefT sbStatusRef;
    @XmlElement(name = "ObsUnitSetRef")
    private ObsProjectRefT obsUnitSetRef;
    @XmlElement(defaultValue = "false")
    private boolean standardMode;
    @XmlElement(required = true)
    private String modeName;
    @XmlElement(name = "pIName", required = true, defaultValue = "Unknown")
    private String piName;
    private List<KeywordValueT> expertParameter;
    private String qa0Notes;
    @XmlElement(name = "OpticalCameraSpec")
    private List<OpticalCameraSpecT> opticalCameraSpec;
    @XmlElement(name = "SpectralSpec")
    private List<SpectralSpecT> spectralSpec;
    @XmlElement(name = "FieldSource")
    private List<FieldSourceT> fieldSource;
    @XmlElement(name = "ObservingGroup")
    private List<ObservingGroupT> observingGroup;
    @XmlElements({
        @XmlElement(name = "AmplitudeCalParameters", type = AmplitudeCalParametersT.class),
        @XmlElement(name = "AtmosphericCalParameters", type = AtmosphericCalParametersT.class),
        @XmlElement(name = "BandpassCalParameters", type = BandpassCalParametersT.class),
        @XmlElement(name = "CheckSourceCalParameters", type = CheckSourceCalParametersT.class),
        @XmlElement(name = "DelayCalParameters", type = DelayCalParametersT.class),
        @XmlElement(name = "FocusCalParameters", type = FocusCalParametersT.class),
        @XmlElement(name = "HolographyParameters", type = HolographyParametersT.class),
        @XmlElement(name = "OpticalPointingParameters", type = OpticalPointingParametersT.class),
        @XmlElement(name = "PhaseCalParameters", type = PhaseCalParametersT.class),
        @XmlElement(name = "PointingCalParameters", type = PointingCalParametersT.class),
        @XmlElement(name = "PolarizationCalParameters", type = PolarizationCalParametersT.class),
        @XmlElement(name = "RadiometricPointingParameters", type = RadiometricPointingParametersT.class),
        @XmlElement(name = "ReservationParameters", type = ReservationParametersT.class),
        @XmlElement(name = "ScienceParameters", type = ScienceParametersT.class),
        @XmlElement(name = "SidebandRatioCalParameters", type = SidebandRatioCalParametersT.class)
    })
    private List<ObservingParametersT> amplitudeCalParametersOrAtmosphericCalParametersOrBandpassCalParameters;
    @XmlElement(name = "ObsProcedure", required = true)
    private ObsProcedureT obsProcedure;
    @XmlElement(name = "Preconditions", required = true)
    private PreconditionsT preconditions;
    @XmlElement(name = "SchedBlockControl", required = true)
    private SchedBlockControlT schedBlockControl;
    @XmlElement(name = "SchedulingConstraints", required = true)
    private SchedulingConstraintsT schedulingConstraints;
    @XmlElement(name = "Target")
    private List<TargetT> target;
    @XmlElement(name = "TemporalConstraints")
    private List<TemporalConstraintsT> temporalConstraints;
    @XmlElement(name = "TimeAllocationBreakdown")
    private TimeAllocationBreakdownT timeAllocationBreakdown;
    @XmlAttribute(name = "schemaVersion", required = true)
    private String schemaVersion;
    @XmlAttribute(name = "revision")
    private String revision;
    @XmlAttribute(name = "almatype", required = true)
    private String almatype;
    @XmlAttribute(name = "modeType")
    private String modeType;

    /**
     * Gets the value of the schedBlockEntity property.
     * 
     * @return
     *     possible object is
     *     {@link SchedBlockEntityT }
     *     
     */
    public SchedBlockEntityT getSchedBlockEntity() {
        return schedBlockEntity;
    }

    /**
     * Sets the value of the schedBlockEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchedBlockEntityT }
     *     
     */
    public void setSchedBlockEntity(SchedBlockEntityT value) {
        this.schedBlockEntity = value;
    }

    /**
     * Gets the value of the sbStatusRef property.
     * 
     * @return
     *     possible object is
     *     {@link SBStatusRefT }
     *     
     */
    public SBStatusRefT getSBStatusRef() {
        return sbStatusRef;
    }

    /**
     * Sets the value of the sbStatusRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SBStatusRefT }
     *     
     */
    public void setSBStatusRef(SBStatusRefT value) {
        this.sbStatusRef = value;
    }

    /**
     * Gets the value of the obsUnitSetRef property.
     * 
     * @return
     *     possible object is
     *     {@link ObsProjectRefT }
     *     
     */
    public ObsProjectRefT getObsUnitSetRef() {
        return obsUnitSetRef;
    }

    /**
     * Sets the value of the obsUnitSetRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObsProjectRefT }
     *     
     */
    public void setObsUnitSetRef(ObsProjectRefT value) {
        this.obsUnitSetRef = value;
    }

    /**
     * Gets the value of the standardMode property.
     * 
     */
    public boolean isStandardMode() {
        return standardMode;
    }

    /**
     * Sets the value of the standardMode property.
     * 
     */
    public void setStandardMode(boolean value) {
        this.standardMode = value;
    }

    /**
     * Gets the value of the modeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModeName() {
        return modeName;
    }

    /**
     * Sets the value of the modeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModeName(String value) {
        this.modeName = value;
    }

    /**
     * Gets the value of the piName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPIName() {
        return piName;
    }

    /**
     * Sets the value of the piName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPIName(String value) {
        this.piName = value;
    }

    /**
     * Gets the value of the expertParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the expertParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExpertParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeywordValueT }
     * 
     * 
     */
    public List<KeywordValueT> getExpertParameter() {
        if (expertParameter == null) {
            expertParameter = new ArrayList<>();
        }
        return this.expertParameter;
    }

    /**
     * Gets the value of the qa0Notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQa0Notes() {
        return qa0Notes;
    }

    /**
     * Sets the value of the qa0Notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQa0Notes(String value) {
        this.qa0Notes = value;
    }

    /**
     * Gets the value of the opticalCameraSpec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the opticalCameraSpec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOpticalCameraSpec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpticalCameraSpecT }
     * 
     * 
     */
    public List<OpticalCameraSpecT> getOpticalCameraSpec() {
        if (opticalCameraSpec == null) {
            opticalCameraSpec = new ArrayList<>();
        }
        return this.opticalCameraSpec;
    }

    /**
     * Gets the value of the spectralSpec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spectralSpec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpectralSpec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpectralSpecT }
     * 
     * 
     */
    public List<SpectralSpecT> getSpectralSpec() {
        if (spectralSpec == null) {
            spectralSpec = new ArrayList<>();
        }
        return this.spectralSpec;
    }

    /**
     * Gets the value of the fieldSource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldSource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldSource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FieldSourceT }
     * 
     * 
     */
    public List<FieldSourceT> getFieldSource() {
        if (fieldSource == null) {
            fieldSource = new ArrayList<>();
        }
        return this.fieldSource;
    }

    /**
     * Gets the value of the observingGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the observingGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObservingGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObservingGroupT }
     * 
     * 
     */
    public List<ObservingGroupT> getObservingGroup() {
        if (observingGroup == null) {
            observingGroup = new ArrayList<>();
        }
        return this.observingGroup;
    }

    /**
     * Gets the value of the amplitudeCalParametersOrAtmosphericCalParametersOrBandpassCalParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the amplitudeCalParametersOrAtmosphericCalParametersOrBandpassCalParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAmplitudeCalParametersOrAtmosphericCalParametersOrBandpassCalParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AmplitudeCalParametersT }
     * {@link AtmosphericCalParametersT }
     * {@link BandpassCalParametersT }
     * {@link CheckSourceCalParametersT }
     * {@link DelayCalParametersT }
     * {@link FocusCalParametersT }
     * {@link HolographyParametersT }
     * {@link OpticalPointingParametersT }
     * {@link PhaseCalParametersT }
     * {@link PointingCalParametersT }
     * {@link PolarizationCalParametersT }
     * {@link RadiometricPointingParametersT }
     * {@link ReservationParametersT }
     * {@link ScienceParametersT }
     * {@link SidebandRatioCalParametersT }
     * 
     * 
     */
    public List<ObservingParametersT> getAmplitudeCalParametersOrAtmosphericCalParametersOrBandpassCalParameters() {
        if (amplitudeCalParametersOrAtmosphericCalParametersOrBandpassCalParameters == null) {
            amplitudeCalParametersOrAtmosphericCalParametersOrBandpassCalParameters = new ArrayList<>();
        }
        return this.amplitudeCalParametersOrAtmosphericCalParametersOrBandpassCalParameters;
    }

    /**
     * Gets the value of the obsProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link ObsProcedureT }
     *     
     */
    public ObsProcedureT getObsProcedure() {
        return obsProcedure;
    }

    /**
     * Sets the value of the obsProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObsProcedureT }
     *     
     */
    public void setObsProcedure(ObsProcedureT value) {
        this.obsProcedure = value;
    }

    /**
     * Gets the value of the preconditions property.
     * 
     * @return
     *     possible object is
     *     {@link PreconditionsT }
     *     
     */
    public PreconditionsT getPreconditions() {
        return preconditions;
    }

    /**
     * Sets the value of the preconditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreconditionsT }
     *     
     */
    public void setPreconditions(PreconditionsT value) {
        this.preconditions = value;
    }

    /**
     * Gets the value of the schedBlockControl property.
     * 
     * @return
     *     possible object is
     *     {@link SchedBlockControlT }
     *     
     */
    public SchedBlockControlT getSchedBlockControl() {
        return schedBlockControl;
    }

    /**
     * Sets the value of the schedBlockControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchedBlockControlT }
     *     
     */
    public void setSchedBlockControl(SchedBlockControlT value) {
        this.schedBlockControl = value;
    }

    /**
     * Gets the value of the schedulingConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link SchedulingConstraintsT }
     *     
     */
    public SchedulingConstraintsT getSchedulingConstraints() {
        return schedulingConstraints;
    }

    /**
     * Sets the value of the schedulingConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchedulingConstraintsT }
     *     
     */
    public void setSchedulingConstraints(SchedulingConstraintsT value) {
        this.schedulingConstraints = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the target property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTarget().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TargetT }
     * 
     * 
     */
    public List<TargetT> getTarget() {
        if (target == null) {
            target = new ArrayList<>();
        }
        return this.target;
    }

    /**
     * Gets the value of the temporalConstraints property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the temporalConstraints property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemporalConstraints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TemporalConstraintsT }
     * 
     * 
     */
    public List<TemporalConstraintsT> getTemporalConstraints() {
        if (temporalConstraints == null) {
            temporalConstraints = new ArrayList<>();
        }
        return this.temporalConstraints;
    }

    /**
     * Gets the value of the timeAllocationBreakdown property.
     * 
     * @return
     *     possible object is
     *     {@link TimeAllocationBreakdownT }
     *     
     */
    public TimeAllocationBreakdownT getTimeAllocationBreakdown() {
        return timeAllocationBreakdown;
    }

    /**
     * Sets the value of the timeAllocationBreakdown property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeAllocationBreakdownT }
     *     
     */
    public void setTimeAllocationBreakdown(TimeAllocationBreakdownT value) {
        this.timeAllocationBreakdown = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        if (schemaVersion == null) {
            return "13";
        } else {
            return schemaVersion;
        }
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevision() {
        if (revision == null) {
            return "24";
        } else {
            return revision;
        }
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevision(String value) {
        this.revision = value;
    }

    /**
     * Gets the value of the almatype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlmatype() {
        if (almatype == null) {
            return "APDM::SchedBlock";
        } else {
            return almatype;
        }
    }

    /**
     * Sets the value of the almatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlmatype(String value) {
        this.almatype = value;
    }

    /**
     * Gets the value of the modeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModeType() {
        if (modeType == null) {
            return "User";
        } else {
            return modeType;
        }
    }

    /**
     * Sets the value of the modeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModeType(String value) {
        this.modeType = value;
    }

}
