/*
 * ALMA - Atacama Large Millimeter Array
 * Copyright (c) UKATC - UK Astronomy Technology Centre, Science and Technology Facilities Council, 2018
 * (in the framework of the ALMA collaboration).
 * All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The Spectral setup for radio observing. This includes the receiver setup and the correlator setup.
 * 
 * <p>Java class for SpectralSpecT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpectralSpecT">
 *   &lt;complexContent>
 *     &lt;extension base="{Alma/ObsPrep/SchedBlock}AbstractInstrumentSpecT">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="ACACorrelatorConfiguration" type="{Alma/ObsPrep/SchedBlock}ACACorrelatorConfigurationT" minOccurs="0"/>
 *           &lt;element name="BLCorrelatorConfiguration" type="{Alma/ObsPrep/SchedBlock}BLCorrelatorConfigurationT" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="BeamSwitchingCycle" type="{Alma/ObsPrep/SchedBlock}BeamSwitchingCycleT" minOccurs="0"/>
 *           &lt;element name="FrequencySwitchingCycle" type="{Alma/ObsPrep/SchedBlock}FrequencySwitchingCycleT" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="FrequencySetup" type="{Alma/ObsPrep/SchedBlock}FrequencySetupT"/>
 *         &lt;element name="SquareLawSetup" type="{Alma/ObsPrep/SchedBlock}SquareLawSetupT" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="switchingType" default="NO_SWITCHING">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="NO_SWITCHING"/>
 *             &lt;enumeration value="LOAD_SWITCHING"/>
 *             &lt;enumeration value="POSITION_SWITCHING"/>
 *             &lt;enumeration value="FREQUENCY_SWITCHING"/>
 *             &lt;enumeration value="PHASE_SWITCHING"/>
 *             &lt;enumeration value="NUTATOR_SWITCHING"/>
 *             &lt;enumeration value="CHOPPER_WHEEL"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="receiverType" default="SSB">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="NOSB"/>
 *             &lt;enumeration value="DSB"/>
 *             &lt;enumeration value="TSB"/>
 *             &lt;enumeration value="SSB"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpectralSpecT", propOrder = {
    "acaCorrelatorConfiguration",
    "blCorrelatorConfiguration",
    "beamSwitchingCycle",
    "frequencySwitchingCycle",
    "frequencySetup",
    "squareLawSetup"
})
public class SpectralSpecT
    extends AbstractInstrumentSpecT
{

    @XmlElement(name = "ACACorrelatorConfiguration")
    private ACACorrelatorConfigurationT acaCorrelatorConfiguration;
    @XmlElement(name = "BLCorrelatorConfiguration")
    private BLCorrelatorConfigurationT blCorrelatorConfiguration;
    @XmlElement(name = "BeamSwitchingCycle")
    private BeamSwitchingCycleT beamSwitchingCycle;
    @XmlElement(name = "FrequencySwitchingCycle")
    private FrequencySwitchingCycleT frequencySwitchingCycle;
    @XmlElement(name = "FrequencySetup", required = true)
    private FrequencySetupT frequencySetup;
    @XmlElement(name = "SquareLawSetup")
    private SquareLawSetupT squareLawSetup;
    @XmlAttribute(name = "switchingType")
    private String switchingType;
    @XmlAttribute(name = "receiverType")
    private String receiverType;

    /**
     * Gets the value of the acaCorrelatorConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link ACACorrelatorConfigurationT }
     *     
     */
    public ACACorrelatorConfigurationT getACACorrelatorConfiguration() {
        return acaCorrelatorConfiguration;
    }

    /**
     * Sets the value of the acaCorrelatorConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACACorrelatorConfigurationT }
     *     
     */
    public void setACACorrelatorConfiguration(ACACorrelatorConfigurationT value) {
        this.acaCorrelatorConfiguration = value;
    }

    /**
     * Gets the value of the blCorrelatorConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link BLCorrelatorConfigurationT }
     *     
     */
    public BLCorrelatorConfigurationT getBLCorrelatorConfiguration() {
        return blCorrelatorConfiguration;
    }

    /**
     * Sets the value of the blCorrelatorConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BLCorrelatorConfigurationT }
     *     
     */
    public void setBLCorrelatorConfiguration(BLCorrelatorConfigurationT value) {
        this.blCorrelatorConfiguration = value;
    }

    /**
     * Gets the value of the beamSwitchingCycle property.
     * 
     * @return
     *     possible object is
     *     {@link BeamSwitchingCycleT }
     *     
     */
    public BeamSwitchingCycleT getBeamSwitchingCycle() {
        return beamSwitchingCycle;
    }

    /**
     * Sets the value of the beamSwitchingCycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeamSwitchingCycleT }
     *     
     */
    public void setBeamSwitchingCycle(BeamSwitchingCycleT value) {
        this.beamSwitchingCycle = value;
    }

    /**
     * Gets the value of the frequencySwitchingCycle property.
     * 
     * @return
     *     possible object is
     *     {@link FrequencySwitchingCycleT }
     *     
     */
    public FrequencySwitchingCycleT getFrequencySwitchingCycle() {
        return frequencySwitchingCycle;
    }

    /**
     * Sets the value of the frequencySwitchingCycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrequencySwitchingCycleT }
     *     
     */
    public void setFrequencySwitchingCycle(FrequencySwitchingCycleT value) {
        this.frequencySwitchingCycle = value;
    }

    /**
     * Gets the value of the frequencySetup property.
     * 
     * @return
     *     possible object is
     *     {@link FrequencySetupT }
     *     
     */
    public FrequencySetupT getFrequencySetup() {
        return frequencySetup;
    }

    /**
     * Sets the value of the frequencySetup property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrequencySetupT }
     *     
     */
    public void setFrequencySetup(FrequencySetupT value) {
        this.frequencySetup = value;
    }

    /**
     * Gets the value of the squareLawSetup property.
     * 
     * @return
     *     possible object is
     *     {@link SquareLawSetupT }
     *     
     */
    public SquareLawSetupT getSquareLawSetup() {
        return squareLawSetup;
    }

    /**
     * Sets the value of the squareLawSetup property.
     * 
     * @param value
     *     allowed object is
     *     {@link SquareLawSetupT }
     *     
     */
    public void setSquareLawSetup(SquareLawSetupT value) {
        this.squareLawSetup = value;
    }

    /**
     * Gets the value of the switchingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwitchingType() {
        if (switchingType == null) {
            return "NO_SWITCHING";
        } else {
            return switchingType;
        }
    }

    /**
     * Sets the value of the switchingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwitchingType(String value) {
        this.switchingType = value;
    }

    /**
     * Gets the value of the receiverType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverType() {
        if (receiverType == null) {
            return "SSB";
        } else {
            return receiverType;
        }
    }

    /**
     * Sets the value of the receiverType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverType(String value) {
        this.receiverType = value;
    }

}
