/*
 * ALMA - Atacama Large Millimeter Array
 * Copyright (c) UKATC - UK Astronomy Technology Centre, Science and Technology Facilities Council, 2018
 * (in the framework of the ALMA collaboration).
 * All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 04:31:38 PM BST 
//


package com.prototype.ot.microservices.projectservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Describes the setup for a long term monitoring type observation, i.e. returning to observe a target on a medium term cadance, e.g. every month.
 * 
 * <p>Java class for VisitConstraintT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VisitConstraintT">
 *   &lt;complexContent>
 *     &lt;extension base="{Alma/ObsPrep/ObsProject}AbstractTimingConstraintsT">
 *       &lt;sequence>
 *         &lt;element name="visitId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="previousVisitId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="requiredDelay" type="{Alma/ValueTypes}TimeT" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VisitConstraintT", namespace = "Alma/ObsPrep/ObsProject", propOrder = {
    "visitId",
    "previousVisitId",
    "requiredDelay"
})
public class VisitConstraintT
    extends AbstractTimingConstraintsT
{

    @XmlElement(defaultValue = "0")
    private int visitId;
    @XmlElement(defaultValue = "0")
    private Integer previousVisitId;
    private TimeT requiredDelay;

    /**
     * Gets the value of the visitId property.
     * 
     */
    public int getVisitId() {
        return visitId;
    }

    /**
     * Sets the value of the visitId property.
     * 
     */
    public void setVisitId(int value) {
        this.visitId = value;
    }

    /**
     * Gets the value of the previousVisitId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPreviousVisitId() {
        return previousVisitId;
    }

    /**
     * Sets the value of the previousVisitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPreviousVisitId(Integer value) {
        this.previousVisitId = value;
    }

    /**
     * Gets the value of the requiredDelay property.
     * 
     * @return
     *     possible object is
     *     {@link TimeT }
     *     
     */
    public TimeT getRequiredDelay() {
        return requiredDelay;
    }

    /**
     * Sets the value of the requiredDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeT }
     *     
     */
    public void setRequiredDelay(TimeT value) {
        this.requiredDelay = value;
    }

}
